### ISSUE TITLE
[Grid] Issue

### ISSUE THREAD

**Issue by andrecasal** [radix-ui/themes#100]
Using `dense` is [bad for accessibility](https://www.matuzo.at/blog/the-dark-side-of-the-grid-part-2/).

Since Radix is accessibility focused, I'd suggest we remove these options?

**Comment by vladmoroz** [comment]
Nothing wrong with dense grids without interactive elements.

**Comment by andrecasal** [comment]
Wouldn't this still confuse users using screen magnifiers because the enlarged portion of the screen skips around and blind users working with sighted users, who read the page in visual order, when they encounter information in a different order?

Are those use cases not considered important enough for accessibility? Genuine question 😊

**Comment by vladmoroz** [comment]
@andrecasal there're many other ways to create much worse accessibility problems using the components and styles that can be used accessibly. This isn't a Radix Themes concern, that's how everything on the web works. We just provide the tools to build your project, it's up to you to do a good job with it.
