### ISSUE TITLE
Shouldn't `DropdownMenu.Content` scroll by default?

### ISSUE THREAD

**Issue by nuthinking** [radix-ui/themes#110]
Hence the various collision options. But the menu gets off the screen. Should I wrap it into a `Scroll Area`? 🤔

Thanks!

**Comment by vladmoroz** [comment]
Can you clarify the issue with an example? In Radix Themes the Dropdown Menu Content component already comes with a built-in Scroll Area:

https://github.com/radix-ui/themes/assets/8441036/bd84de62-f43d-41eb-bde1-fbf6591c56e2

**Comment by nuthinking** [comment]
Thanks @vladmoroz for confirming this! It doesn't work for me though. This is my code, in a nutshell:

```typescript
export const TeamSwitcher: React.FC<Props> = props => {
    const { teams, currentTeamId, onChange, onCreateNew } = props;
    const [portalContainer] = useState(() => document.getElementById("portal"));

    const currentTeam = defined(teams.find(t => t.id === currentTeamId));

    return (
        <DropdownMenu.Root>
            <DropdownMenu.Trigger tw="w-full p-2 flex items-center justify-center gap-3 rounded-xl hover:bg-n200A data-[state=open]:bg-n200A">
                <TeamListItem team={currentTeam} selected={false} />
            </DropdownMenu.Trigger>

            <DropdownMenu.Portal container={portalContainer}>
                <DropdownMenu.Content tw="p-1 min-w-[248px] shadow-md-dark bg-bg-front rounded-lg" align="start">
                    {teams.map(t => (
                        <DropdownMenu.Item
                            tw="p-2 hover:bg-n200A data-[highlighted]:bg-n200A rounded-xl"
                            key={t.id}
                            onClick={() => onChange(t.id)}>
                            <TeamListItem team={t} selected={t.id === currentTeamId} />
                        </DropdownMenu.Item>
                    ))}
                </DropdownMenu.Content>
            </DropdownMenu.Portal>
        </DropdownMenu.Root>
    );
};
```

Even without passing our portal doesn't work 🤷‍♂️

**Comment by nuthinking** [comment]
The documentation example doesn't scroll either: https://codesandbox.io/s/jovial-carlos-wlzjnh

**Comment by vladmoroz** [comment]
@nuthinking your examples import the [Dropdown Menu primitive](https://www.radix-ui.com/primitives/docs/components/dropdown-menu) which comes with no presentational styles like scroll. If that's what you wanted to use, you'll have to add an overflow style yourself or compose it with the Scroll Area.

If you wanted a [themed Dropdown Menu component](https://www.radix-ui.com/themes/docs/components/dropdown-menu)  which comes with pre-defined styles and is pre-composed with the Scroll Area, you should get it from the `@radix-ui/themes` package

**Comment by nuthinking** [comment]
Gotcha! Adding `overflow-y: auto` to the content doesn't do anything. The element height is not modified. Any idea where I can find an example? I would prefer not using the themed version. Thanks a lot! 🙏

**Comment by vladmoroz** [comment]
@nuthinking you need to add max-height to enable overflow. You can use `--radix-dropdown-menu-content-available-height` variable for that, here’s an example:
https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/components/dropdown-menu.css

**Comment by nuthinking** [comment]
@vladmoroz thank you so much!
