### ISSUE TITLE
Styles are just buggy.

### ISSUE THREAD

**Issue by devlzcode** [radix-ui/themes#115]
> This is just one instance of the issue with styling I've been experiencing with radix-ui themes. I'd love to continue using this library but at this point I've spent more time trying to debug or get consistency in styling cause of problems when I could be getting my product ready.

**next 13.5.4**
**radix-themes 2.0.0**

Styles just don't apply sometimes, especially on buttons (I've seen it happen with inputs too). These buttons should both be the accent color, but they are not:
<img width="535" alt="image" src="https://github.com/radix-ui/themes/assets/58056533/bb9ef78d-4b6c-4252-95d4-0b331a0b77ee">
```ts
export function LoginModal({ isOpen, onClose }) {
  return (
    <Dialog.Root open={isOpen}>
      <Dialog.Content className="max-w-md">
        <Dialog.Title>Login</Dialog.Title>
        <Dialog.Description className="mb-4">
          Please enter your account name and password.
        </Dialog.Description>
        <form className="space-y-4">
          <label htmlFor="account_name">
            <span className="mb-1">Account Name</span>
            <TextField.Root>
              <TextField.Input id="account_name" />
            </TextField.Root>
          </label>
          <div className="space-x-2">
            <Dialog.Close>
              <Button>Cancel</Button>
            </Dialog.Close>
            <Dialog.Close>
              <Button>Submit</Button>
            </Dialog.Close>
          </div>
        </form>
      </Dialog.Content>
    </Dialog.Root>
  );
}
```

Here is the same issue but using the code from the dialog documention of radix themes:
<img width="468" alt="Screenshot 2023-10-12 at 4 36 08 PM" src="https://github.com/radix-ui/themes/assets/58056533/06e5d340-07c2-4f83-90d6-5e159a4ee7e3">

**Comment by vladmoroz** [comment]
Looks like Tailwind base overwrites Radix Themes classes in your case.

See https://github.com/radix-ui/themes/issues/109#issuecomment-1747345743 for the solution.

If you use Tailwind just for its layout utilities, I'd recommend to give Radix Themes layout components a try instead.
