### ISSUE TITLE
[Next.js][Bug] Typography fails to load

### ISSUE THREAD

**Issue by jwala-anirudh** [radix-ui/themes#117]
## Background
Following the [guide](https://www.radix-ui.com/themes/docs/theme/typography#with-nextfont) of setting `Inter` font on next.js application is fails to swap the font-family property with the default

## Steps

1. Created nextjs application (v13.5.4)
2. Install radix-themes (v2.0.0)
3. Updated `layout.tsx` with following
    - New import for `theme-config.css`
    - Update the `inter` object with display &  `variable` attributes
4. Updated `className` for body (as per docs it is mentioned to add at the `<html>` tag level which doesn't work)
5. End up with console error as below
![image](https://github.com/radix-ui/themes/assets/25549847/66357b4c-6719-4c7c-aef5-d39c9385af53)
6. Inspected DOM element (for example that sets to default font)
![image](https://github.com/radix-ui/themes/assets/25549847/f877d532-e752-4da1-a455-17623608d66a)

## Code snippets

1) layout.tsx
```typescript
import '@radix-ui/themes/styles.css';
import './theme-config.css';

import { Inter } from 'next/font/google';
import { Theme } from '@radix-ui/themes';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
```

2. theme-config.css

```css
.radix-themes {
  --default-font-family: var(--font-inter);
}
```

**Comment by devalpi** [comment]
This warning message indicates that there are some extra attributes on the HTML element that Next.js received from the server that it does not recognize. These attributes are added by various browser extensions, plugins, or toolbars that modify the HTML of the page.

Adding `suppressHydrationWarning={true}` may seem like a sufficient solution, but when developing with Next.js, you might encounter the same error after a hot reload.

Temporarily disable browser extensions, except for those required for development in your browser. 
Easy way to disable extensions on URLs you develop: [chrome://flags/#extensions-menu-access-control](url)

**Comment by jwala-anirudh** [comment]
Thanks for you response @devalpi, agree with your point on Next.js acting up when special attributes are added to HTML elements. Coming to the temporary fix `suppressHydrationWarning` was not able to remove the console error.

Although I am fine with the console error, but my concern is still that font-family that I apply doesn't get computed onto the elements on final render; which I was expecting to happen as per the guide provided

**Comment by jwala-anirudh** [comment]
Fantastic, thanks @nikasepiskveradze that resolves the error from the console. Additionally I was able to fix the issue with `font-family` in the following format 🙂

```css
.radix-themes {
  --default-font-family: var(--font-inter) !important;
}
```

**Comment by vladmoroz** [comment]
I'll reopen this so that we remember to double-check how Radix Themes works with next/font

**Comment by fabianvieri** [comment]
Got same issue, any workaround without using` css !important` ?

**Comment by vladmoroz** [comment]
We looked into this the other day and noticed that Next 13 doesn't always respect the order of CSS imports in layout files, placing Radix styles after your custom CSS.

Try importing Radix Themes stylesheet within your own CSS (with postcss-import or another tech) or import CSS on the page itself.

**Comment by gael37** [comment]
> Fantastic, thanks @nikasepiskveradze that resolves the error from the console. Additionally I was able to fix the issue with `font-family` in the following format 🙂
> 
> ```css
> .radix-themes {
>   --default-font-family: var(--font-inter) !important;
> }
> ```

Thanks so much! the '!important' works I was stuck on it for ages

**Comment by helioswebinc** [comment]
@jwala-anirudh Thank you for the `!important` suggestion!

As @vladmoroz mentioned, I kept seeing my definition for `--default-font-family: var(--font-urbanist)` (I'm using Urbanist instead of Inter) striked-out like something in another CSS import was overriding it.

And for the record, I'm using Next 14.0.3 so the import of CSS modules doesn't seem to have improved from the Next 13 that was mentioned above.

**Comment by kbrgl** [comment]
> We looked into this the other day and noticed that Next 13 doesn't always respect the order of CSS imports in layout files, placing Radix styles after your custom CSS.
> 
> Try importing Radix Themes stylesheet within your own CSS (with postcss-import or another tech) or import CSS on the page itself.

This works. For anyone that finds this issue:

```css
@import "@radix-ui/themes/styles.css";

.radix-themes {
    --default-font-family: var(--sans);
}

```

in my globals.css fixed it.

**Comment by vladmoroz** [comment]
We documented this issue and a workaround in the docs:
https://www.radix-ui.com/themes/docs/overview/styling#nextjs-import-order

**Comment by subrotoice** [comment]
> Fantastic, thanks @nikasepiskveradze that resolves the error from the console. Additionally I was able to fix the issue with `font-family` in the following format 🙂
> 
> ```css
> .radix-themes {
>   --default-font-family: var(--font-inter) !important;
> }
> ```
Close and Done

**Comment by system-administration** [comment]
> > We looked into this the other day and noticed that Next 13 doesn't always respect the order of CSS imports in layout files, placing Radix styles after your custom CSS.
> > Try importing Radix Themes stylesheet within your own CSS (with postcss-import or another tech) or import CSS on the page itself.
> 
> This works out of the box on Next.js (I’m using 14 with the app dir). For anyone that finds this issue:
> 
> ```css
> @import "@radix-ui/themes/styles.css";
> 
> .radix-themes {
>     --default-font-family: var(--sans);
> }
> ```
> 
> in my globals.css fixed it.

Thanks so much! I added the import line at the top and it seemed to do the trick! Its rendering my preferred font now.

**Comment by shiva2021** [comment]
> > We looked into this the other day and noticed that Next 13 doesn't always respect the order of CSS imports in layout files, placing Radix styles after your custom CSS.
> > Try importing Radix Themes stylesheet within your own CSS (with postcss-import or another tech) or import CSS on the page itself.
> 
> This works out of the box on Next.js (I’m using 14 with the app dir). For anyone that finds this issue:
> 
> ```css
> @import "@radix-ui/themes/styles.css";
> 
> .radix-themes {
>     --default-font-family: var(--sans);
> }
> ```
> 
> in my globals.css fixed it.

This fixed the issue for me and also seems to be a standard way to dealing with this problem. `!important` feels dirty for some reason 😅
