### ISSUE TITLE
[AlertDialog] Issue

### ISSUE THREAD

**Issue by machineman10** [radix-ui/themes#123]
im using nextjs 13.5.4. working well on development but buttons not showing in next build

**Comment by machineman10** [comment]
> Can you share more details or a repro?

<AlertDialogRoot>
        <AlertDialogTrigger>
          <Button
            color="red"
            style={{ backgroundColor: "var(--accent-11)" }}
            className="cursor-pointer"
            disabled={isDeleting}
          >
            <TrashIcon />
            <Text>Delete issue</Text>
            {isDeleting && <Spinner />}
          </Button>
        </AlertDialogTrigger>
        <AlertDialogContent>
          <AlertDialogTitle>Confirm Deletion</AlertDialogTitle>
          <AlertDialogDescription>
            Do you want to permanently delete this issue?
          </AlertDialogDescription>

          <Flex mt="4" gap="3" justify="end">
            <AlertDialogCancel>
              <Button
                variant="soft"
                color="gray"
                style={{ backgroundColor: "var(--accent-a3)" }}
                className="cursor-pointer"
              >
                Cancel
              </Button>
            </AlertDialogCancel>
            <AlertDialogAction>
              <Button
                color="red"
                style={{ backgroundColor: "var(--accent-11)" }}
                variant="solid"
                className="cursor-pointer"
                onClick={deleteHandler}
              >
                Delete
              </Button>
            </AlertDialogAction>
          </Flex>
        </AlertDialogContent>
      </AlertDialogRoot>

I had to add inline background color to make these buttons visible. works fine on dev but in production build I'm seeing a backgroundColor: transparent style from radix ui theme css, in all of the buttons inside AlertDialog. Also, buttons inside AlertDialog are not cursor-pointer by default.

**Comment by vladmoroz** [comment]
The transparent background color is caused by an overzealous Tailwind reset, see this comment for solution:
https://github.com/radix-ui/themes/issues/109#issuecomment-1747345743

> Also, buttons inside AlertDialog are not cursor-pointer by default.

This is the default browser behaviour which Radix Themes respects. If you want pointer cursors, you can create add a style that overrides these variables on the `.radix-themes` selector:
https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/styles/tokens/cursor.css

**Comment by machineman10** [comment]
> If you are using Tailwind, the transparent background color is likely caused by an overzealous Tailwind reset, see this comment for solution: [#109 (comment)](https://github.com/radix-ui/themes/issues/109#issuecomment-1747345743)
> 
> > Also, buttons inside AlertDialog are not cursor-pointer by default.
> 
> This is the default browser behaviour which Radix Themes respects. If you want pointer cursors, you can create add a style that overrides these variables on the `.radix-themes` selector: https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/styles/tokens/cursor.css

Worked. Thanks 🥳
