### ISSUE TITLE
[Button] Not a pointer?

### ISSUE THREAD

**Issue by BokaiWang** [radix-ui/themes#126]
It seems that you guys made the cursor on a button not a pointer on purpose
I tried adding a Tailwind class (cursor-pointer) to make the cursor a pointer, but it didn't work
I was wondering how I can make it a pointer...

**Comment by kevinmitch14** [comment]
https://github.com/radix-ui/themes/issues/123#issuecomment-1778862252

**Comment by randysmachado** [comment]
Same problem.
Variables are not being modified
[https://www.radix-ui.com/themes/docs/theme/token-reference#modifying-tokens](https://www.radix-ui.com/themes/docs/theme/token-reference#modifying-tokens)

Radix theme: 2.0.0
NextJS: 14.0.1



![radix-config](https://github.com/radix-ui/themes/assets/25080392/c8839b00-cc24-4bb3-8536-37abf454f62b)

![theme-config](https://github.com/radix-ui/themes/assets/25080392/6fe7b855-4f3f-4d94-ba75-0e4e98fb9332)

![html](https://github.com/radix-ui/themes/assets/25080392/15adbae7-14c2-44bd-8469-75bee93fb5d4)

**Comment by SilviuIordache** [comment]
I have the same issue, has this been fixed?
