### ISSUE TITLE
[Select] asChild props is not available on Select.Trigger

### ISSUE THREAD

**Issue by ladislasdellinger** [radix-ui/themes#133]
Hello all,

I've noticed a minor discrepancy in the documentation for Select.Trigger. The documentation currently states that it accepts the `asChild` props, but in practice, it doesn't.

Upon further investigation, it appears that this prop is not supported, suggesting that there may be a documentation error. 😊

**Comment by sannajammeh** [comment]
Same with the DropdownMenu. It should be documented that the trigger accepts a button as a child component without the use of `asChild`

**Comment by Teddarific** [comment]
Just ran into this as well. 
<img width="923" alt="image" src="https://github.com/radix-ui/themes/assets/16343600/d11a5c7e-86c7-4fa7-9e93-5c100ed5543f">

Seems like the documentation needs to be updated.

**Comment by vladmoroz** [comment]
We’ll update the docs. What outcome were you expecting when using `asChild` though? The trigger comes with its own styles, so if `asChild` were supported, it would have merged its styles with the child element. Is this what you waned to achieve?

**Comment by vladmoroz** [comment]
We'll update this in the docs for 3.0.0
