### ISSUE TITLE
[Tooltip] Issue

### ISSUE THREAD

**Issue by DaveBitter** [radix-ui/themes#134]
The example for the Tooltip component seems to not be working on [the docs page](https://www.radix-ui.com/themes/docs/components/tooltip). When clicking the button, nothing happens.

When inspecting the DOM, it appears it's opening and directly closing the tooltip.

**Comment by vladmoroz** [comment]
The tooltips opens when it's hovered or receives focus and closes when the trigger is clicked, this is by design. See more in the [primitive doc](https://www.radix-ui.com/primitives/docs/components/tooltip).

If you are looking for a component that opens on click, check out the popover.
