### ISSUE TITLE
Theme could support `as="body"`

### ISSUE THREAD

**Issue by fotinakis** [radix-ui/themes#135]
I'm not sure if this is a idea with unintended consequences/problems, but wanted to throw it out there.

The documented way to use `Theme` is to nest inside of body:

```html
<body>
  <Theme>...everything else...</Theme>
</body>
```

However, if you have components that are built using Radix Primitives directly (either custom, or such as the [Dialog component in shadcn](https://ui.shadcn.com/docs/components/dialog), or if in a project with another headless library like [Headless UI](https://headlessui.com/)) — the Dialog ends up creating a portal which by default is put into the `<body>` tag, so the DOM becomes effectively:
```html
<body>
  <Theme>...everything else...</Theme>
  <Portal>...dialog content...</Portal>
</body>
```

This create the problem: the dialog content is not inside the Theme, so it is missing the configured theme styles etc.

Workarounds include:
* Nesting a second `Theme` inside the Dialog content, and using `useThemeContext()` to grab the root theme's props to pass through
* Or passing a `container` ref through ([comment](https://github.com/radix-ui/primitives/issues/760#issuecomment-952102287))

However, my instinct was to try to do this:

```html
<Theme as="body">
  ...everything else...
</Theme>
```
...which, if supported, I believe would fix all of these issues naturally because the theme element would actually be the top-level body element.

Possible?

**Comment by kevinmitch14** [comment]
I ran into the same issue. What I did was the same as the [DropdownMenu Implementation](https://github.com/radix-ui/themes/blob/bfab82fac4707e5ab633aebd702f5c985c45c019/packages/radix-ui-themes/src/components/dropdown-menu.tsx#L59C1-L92).

```js
// Using shadcn/ui <Select>
<SelectPrimitive.Portal>
    <Theme asChild>
        <SelectPrimitive.Content
            ...
        </SelectPrimitive.Content>
    </Theme>
</SelectPrimitive.Portal>

```

**Comment by fotinakis** [comment]
In my use case (using shadcn/ui `<Sheet>`), doing that errors on click: `Error: React.Children.only expected to receive a single React element child.` (I have not checked this in isolation but in a Remix app, so there could be something else going on here)

**In any case, part of my argument above is that all of these "other" ways are just workarounds**. If it's possible to make the `Theme` element just _be_ the `body` element, then maybe no workarounds would be needed.

**Comment by vladmoroz** [comment]
Theme component supports the `asChild` prop, however I am not sure whether any framework would work well with this when applied to `body`.

We apply Theme with `asChild` onto the content part of the portalled components. If you want to copy your Theme settings, instead of using context it might be easier to create a wrapped Theme component with pre-set props for use in your custom portalled components.
