### ISSUE TITLE
Add "as"-Prop to Flex-Component

### ISSUE THREAD

**Issue by alexmuzenhardt** [radix-ui/themes#136]
### Problem:
Imagine code like this.
```
<header>
    <Flex justify="between">
        <Heading>This is the heading</Heading>
        <Button>I am a button</Button>
    </Flex>
</header>
```

I have to wrap the Flex-Component with a header-Element for A11Y-purposes and semantics.

### Solution:
It would be great if the Flex-Component would have an "as"-Prop to make the Flex-Element an header directly.
```
<Flex as="header" justify="between">
    <Heading>This is a heading</Heading>
    <Button>I am a button</Button>
</Flex>
```

**Comment by vladmoroz** [comment]
Flex supports `asChild` which covers this case
https://www.radix-ui.com/themes/docs/components/flex#api-reference
