### ISSUE TITLE
[Select] Select.Trigger slot for rendering content within trigger

### ISSUE THREAD

**Issue by adrekic** [radix-ui/themes#140]
Have found a couple use cases where it would be desirable to have the ability to render custom content within the default Select.Trigger component. For example, rendering an IconButton that could be used to clear the currently selected value:

![image](https://github.com/radix-ui/themes/assets/90000402/6834114f-745b-471a-aade-4ff3bc4986eb)

Thinking that this would function similarly to TextField.Slot, something like Select.Slot where it could be specified before and after Select.Trigger to get content on the left and right of the placeholder text.

**Comment by henryStelle** [comment]
Yes, this appears to be related to https://github.com/radix-ui/themes/issues/128

**Comment by vladmoroz** [comment]
Let's consolidate with #128
