### ISSUE TITLE
[Dialog] Full-screen dialog layout without margin

### ISSUE THREAD

**Issue by abisao1** [radix-ui/themes#142]
Unable to make dialog fit full screen without any margin/padding around it. Is there anything I am missing or that functionality is not supported?

**Comment by vladmoroz** [comment]
Not with Radix Themes Dialog, but it you can use the Dialog primitive itself to create a full-screen dialog:
https://www.radix-ui.com/primitives/docs/components/dialog

**Comment by vladmoroz** [comment]
Closing as it's not something planned for Radix Themes

**Comment by aryankarim** [comment]
> Unable to make dialog fit full screen without any margin/padding around it. Is there anything I am missing or that functionality is not supported?
 
For radix/themes dialog, one workaround is adding these CSS styles:
```javascript
<Dialog.Content
  style={{
    position: "absolute",
    top: "0",
    left: "0",
    right: "0",
    bottom: "0",
    maxWidth: "100%",
    borderRadius: 0,
  }}
>
```
