### ISSUE TITLE
[Popover] Issue

### ISSUE THREAD

**Issue by abisao1** [radix-ui/themes#144]
Unhandled Runtime Error

Error: Could not find the module "/Users/hassan/Desktop/Projects/NextJS/pms/node_modules/@radix-ui/themes/dist/esm/components/popover.js#Popover#Root" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
Call Stack
<unknown>
/Users/hassan/Desktop/Projects/NextJS/pms/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:260179)
eM
/Users/hassan/Desktop/Projects/NextJS/pms/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:260374)
<unknown>
/Users/hassan/Desktop/Projects/NextJS/pms/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:274925)
Array.toJSON
/Users/hassan/Desktop/Projects/NextJS/pms/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:276115)
stringify
<anonymous>
<unknown>
/Users/hassan/Desktop/Projects/NextJS/pms/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:262475)
ez
/Users/hassan/Desktop/Projects/NextJS/pms/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:262554)
eB
/Users/hassan/Desktop/Projects/NextJS/pms/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:262955)
Timeout._onTimeout
/Users/hassan/Desktop/Projects/NextJS/pms/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:259453)
listOnTimeout
node:internal/timers (573:17)
process.processTimers
node:internal/timers (514:7)

**Comment by LauraBeatris** [comment]
Hey @abisao1 👋🏻 

If I understood correctly by the error stack, are you rendering the `Popover` component in a server component? Could you give more details on how you reproduced that error?

**Comment by LauraBeatris** [comment]
This is probably related: https://github.com/radix-ui/themes/issues/138#issuecomment-1794441559
