### ISSUE TITLE
Proposal: Black/White theming

### ISSUE THREAD

**Issue by kevinmitch14** [radix-ui/themes#145]
The Radix colors are really well designed but when building a black/white UI I am a bit lost. Yes I can use `highContrast` on components w/ gray accent but if I switch the theme from gray to something else then I have unwanted highContrast colors. Is there a solution to this?

Basic use-case = using a black background button w/ white text on light appearance settings / a white button background w/ black text on dark appearance settings. But also having the regular colors for other accents.

**Comment by vladmoroz** [comment]
What API do you have in mind when it comes to using it? If I understand you correctly, you could base it on the gray scales, but overwrite gray 9 and gray 10 with your CSS variables, and keep the other accents as is.

I'd absolutely love to feature a community-made black & white theme for Radix Themes.

**Comment by kevinmitch14** [comment]
Yeah I was thinking something similar, overwriting the `--gray-9` & `--gray-10`. Just need to make sure that I am covering everything though, `--gray-9-contrast` would have to be overwritten also AFAIK along with any others I may be forgetting.

What would be the easiest way to make sure I'm covering everything? Run the [playground](https://www.radix-ui.com/themes/playground) locally maybe? Any devtool tricks?

**Comment by vladmoroz** [comment]
Yeah, just clone the repo, `yarn` and then `yarn dev` from the root folder. There's a couple pages like `/sink` and `/explore-components` that would give you a good idea of how your changes are looking

**Comment by kevinmitch14** [comment]
Currently trying out the following most basic approach possible. Will update if I run into anything unexpected.

```css
.radix-themes {
  --gray-9: var(--gray-12);
  --gray-9-contrast: var(--gray-1);
  --gray-10: var(--gray-12);
}

```
