### ISSUE TITLE
global scope

### ISSUE THREAD

**Issue by needim** [radix-ui/themes#15]
https://github.com/radix-ui/themes/blob/39f5a438db0d8496134d4bc35d71899fee1b2562/packages/radix-ui-themes/src/styles/tokens.css#L8C16-L8C16

These tokens should be in :root namespace.

**Comment by jd-carroll** [comment]
Not sure I follow, is there a reason they need to be in the root namespace?

If they are placed in the root namespace then nesting of theme scaling wouldn't be possible.

Take a look at this example which shows the ability to do nested scaling:
https://codesandbox.io/s/intelligent-framework-2xqjp8?file=/src/App.tsx

Note: The sizes are a little difficult (they look similar), but if you right click and view the actual `font-size` of the headings, you'll see the difference

**Comment by needim** [comment]
agreed.

**Comment by magicspon** [comment]
I'm a bit confused... Shouldn't I be able to set `--scaling: 2` anywhere in the dom and for all nested values to use this scaling value.  

```
:root {
  --scaling: 1;
   --spacing-5: calc(2rem * var(--scaling))
}

.my-node {
  --scaling: 2
}
```

why is my-node scaling not applying to child elements... Am i missing something
