### ISSUE TITLE
[TextField] TextField slots with Tailwind (Next14)

### ISSUE THREAD

**Issue by TomBell95** [radix-ui/themes#157]
I'm trying to create a dynamic TextField with slots for icons, however the slots are not working as expected? I've seen issues similar to [CSS specificity issues w/ tailwind #109](https://github.com/radix-ui/themes/issues/109#issuecomment-1747345743) but trying this solution has not worked... 

Does anyone have any suggestions?

Docs: [Themes/TextField](https://www.radix-ui.com/themes/docs/components/text-field)

## TextField component
```javascript
import { joinClassNames } from '@/src/utils'
import * as Label from '@radix-ui/react-label'
import { TextField } from '@radix-ui/themes'
import { ReactNode } from 'react'

type TextInputType = 'text' | 'email' | 'password' | 'number' | 'submit'

interface TextInputProps {
  id: string
  type?: TextInputType
  labelText?: string
  placeholderText?: string
  labelClasses?: string
  inputClasses?: string
  disabled?: boolean
  leftIcon?: ReactNode
  rightIcon?: ReactNode
}

export const TextInput: React.FC<TextInputProps> = ({
  id,
  type = 'text',
  labelText,
  placeholderText,
  disabled,
  inputClasses,
  leftIcon,
  rightIcon,
}) => {
  return (
    <div>
      {labelText && (
        <Label.Root className='text-[15px] font-medium leading-[35px] ' htmlFor='firstName'>
          {labelText}
        </Label.Root>
      )}
      <TextField.Root className='flex justify-between items-center'>
        {leftIcon && <TextField.Slot>{leftIcon}</TextField.Slot>}
        <TextField.Input
          id={id}
          type={type}
          placeholder={placeholderText}
          className={joinClassNames('py-1.5 px-4', inputClasses ? inputClasses : '')}
          disabled={disabled}
        />
        {rightIcon && <TextField.Slot>{rightIcon}</TextField.Slot>}
      </TextField.Root>
    </div>
  )
}

```

## package.json
```
{
  ...
  "@radix-ui/themes": "^2.0.0",
  "autoprefixer": "10.4.15",
  "next": "14.0.0",
  "postcss": "8.4.28",
  "tailwindcss": "3.3.3"
  ...
}
```

**Comment by vladmoroz** [comment]
What's not working exactly?

**Comment by TomBell95** [comment]
> What's not working exactly?

I would expect the icons to be within the input style as per the docs?
![Screenshot 2023-11-22 at 08 31 06](https://github.com/radix-ui/themes/assets/77151052/bcf3d351-2c7e-4e3f-8f52-bddac947a7b8)

**Comment by TomBell95** [comment]
@vladmoroz Here is a quick example - on [CodeSandbox](https://codesandbox.io/p/devbox/suspicious-water-hq3ft9?file=%2Fapp%2Fcomponents%2FTextInput%2Findex.tsx%3A26%2C16&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp9w4lj600093b6k4swxfn4w%2522%252C%2522sizes%2522%253A%255B81.01813110181311%252C18.98186889818689%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp9w4lj600033b6k3g06vko4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp9w4lj600063b6k2qlsvv2q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp9w4lj600083b6kc042bp2b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B53.070710301673294%252C46.929289698326706%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp9w4lj600033b6k3g06vko4%2522%253A%257B%2522id%2522%253A%2522clp9w4lj600033b6k3g06vko4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp9xgq3n00033b6ka7ew0axg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A26%252C%2522startColumn%2522%253A16%252C%2522endLineNumber%2522%253A26%252C%2522endColumn%2522%253A16%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fcomponents%252FTextInput%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp9xgq3n00033b6ka7ew0axg%2522%257D%252C%2522clp9w4lj600083b6kc042bp2b%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp9w4lj600073b6kjtmevr9w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3001%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clp9w4lj600083b6kc042bp2b%2522%252C%2522activeTabId%2522%253A%2522clp9w4lj600073b6kjtmevr9w%2522%257D%252C%2522clp9w4lj600063b6k2qlsvv2q%2522%253A%257B%2522id%2522%253A%2522clp9w4lj600063b6k2qlsvv2q%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp9w4lj600043b6kuw8ieqpz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clp9w4lj600053b6k1dgy4n6d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp1zlxc1000gedjw0kvy7j6h%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp9w4lj600043b6kuw8ieqpz%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) - I would expect that without having to update styles the icon is placed in the correct position? And also able to apply the styles to the Root that encompasses both icon and input?

**Comment by vladmoroz** [comment]
Oh, I see. You are not importing Radix Themes CSS, please follow the docs guide:
https://www.radix-ui.com/themes/docs/overview/getting-started

It's not unstyled like the primitives, this is an opinionated component library with its own styles.

If you plan to continue using Radix Themes with Tailwind, make sure to check out [this issue](https://github.com/radix-ui/themes/issues/109#issuecomment-1747345743) as the Tailwind reset overwrites our styles.
