### ISSUE TITLE
[Grid] Issue - can columns be a responsive prop?

### ISSUE THREAD

**Issue by penx** [radix-ui/themes#160]
Seems like the `columns` prop of Grid should be a responsive prop, unless I'm missing something? Happy to contribute a PR if it helps?

https://www.radix-ui.com/themes/docs/components/grid#api-reference

**Comment by penx** [comment]
Not sure if I was using an older version when I raised this, but I can see this _is_ a responsive prop, so this is just a docs issue

<img width="570" alt="Screenshot 2023-12-01 at 12 25 57" src="https://github.com/radix-ui/themes/assets/1027024/8cef659c-c4a6-4698-bc08-47d4480c9448">

**Comment by vladmoroz** [comment]
We'll update this in the docs for 3.0.0
