### ISSUE TITLE
Radix Themes styles missing when components render outside root div

### ISSUE THREAD

**Issue by ajdiyassin** [radix-ui/themes#165]
I had an issue where radix styles were missing, after some debugging the CSS variables weren't applying because selectors are relying on data attributes that only exist in the parent div that is used to render the main app.

For my use case, I needed a Drawer/Sheet that renders outside that div

I fixed this by hard-coding these attributes inside my div.

 ```
     class='radix-themes '
      data-is-root-theme='true'
      data-accent-color='amber'
      data-gray-color='gray'
      data-has-background='false'
      data-panel-background='solid'
      data-radius='medium'
      data-scaling='100%'
```

a better solution to apply these attributes on the body tag

**Comment by ajdiyassin** [comment]
Another solution is to wrap comp in a Theme provider. but idk if that's recommended

**Comment by vladmoroz** [comment]
If your component is portalled, just wrap its content in the Theme provider. You can even `asChild` it to avoid having an extra DOM node.

That's how all Radix Themes portalled components like dialog and popover are built too.

**Comment by vladmoroz** [comment]
Hardcoding those data-attributes is not recommended because they may change down the line. Also, the root Theme component passes all its prop values to children Themes via React context.
