### ISSUE TITLE
[Types]: PropsWithOutRef vs ComponentPropsWithRef

### ISSUE THREAD

**Issue by jd-carroll** [radix-ui/themes#17]
I think this is a bug:
https://github.com/radix-ui/themes/blob/39f5a438db0d8496134d4bc35d71899fee1b2562/packages/radix-ui-themes/src/helpers/props/color.prop.ts#L11-L14

Shouldn't it be:
```jsx
type PropsWithoutRefOrColor<T extends React.ElementType> = Omit<
  React.ComponentPropsWithoutRef<T>,
  'color'
>;
```

Note the change to `React.ComponentPropsWithoutRef<T>`

**Comment by vladmoroz** [comment]
This is probably just an incorrect name of an internal type, I'll close this as there seems to be no actual issue that a user would experience.
