### ISSUE TITLE
Is it possible to get access to all the code of the live examples?

### ISSUE THREAD

**Issue by martiserra99** [radix-ui/themes#170]
Hello, I would love to get access to the code of the live examples. I looked at the github and this code is not in it. I attached a picture with the components I would love to get access to.

<img width="952" alt="Captura de pantalla 2023-12-04 a les 11 59 51" src="https://github.com/radix-ui/themes/assets/99871297/8f1032d8-05c4-4581-a14e-47ef6542709d">

**Comment by kotAPI** [comment]
You can check it on https://github.com/radix-ui/website/blob/main/pages/index.tsx

**Comment by StephenHaney** [comment]
We're looking to make it easy to grab these templates from the website itself, but for now definitely just use the website repo as kotAPI linked.
