### ISSUE TITLE
[Tooltip] Doesn't Work on Safari

### ISSUE THREAD

**Issue by Alek99** [radix-ui/themes#171]
Hello, I was going through the theme playground and noticed the tooltip doesn't work on Safari.

**Comment by kotAPI** [comment]
Can you attach your code and some screenshots?

**Comment by vladmoroz** [comment]
It works for me in Safari 17.1

<img width="263" alt="image" src="https://github.com/radix-ui/themes/assets/8441036/90f28b33-f37b-4e9b-8190-62b0b8a1e62b">
