### ISSUE TITLE
[DecorativeBox] Issue

### ISSUE THREAD

**Issue by btniq** [radix-ui/themes#179]
Hello, I am new to Radix ui, while trying the components with the documentation, I saw that the component named "DecorativeBox" gave an error in all kinds of scenarios, I think this is a mistake, information about the version and errors are as follows.

---
  "@radix-ui/themes": "^2.0.2",
   "react": "^18.2.0",
   "react-dom": "^18.2.0"
   "node version": 18 

does not provide an export named 'DecorativeBox' 

nodule is not available for module and package and I could not find any information about it why there is no information about it or is it purely representative

**Comment by vladmoroz** [comment]
It's not exported in Radix Themes, it's just a component used in docs for illustrative purposes when demonstrating layout elements that don't have any visual aspect to them.

**Comment by aaa3334** [comment]
I am confused.. it is used in the examples everywhere but its not a part of the actual code?

**Comment by benoitgrelard** [comment]
Yes it's a component that's only exposed to our docs MDX file so we can render it in our docs but it's not a component that intended to be part of the package for users to use.

**Comment by karol-may** [comment]
This is ridiculous. Why bother adding to examples sth i can't copy and try?

**Comment by Shivam-Kumar9** [comment]
wese name ka koi dependency ha he nahi jo example me de rakha ha  amazing

**Comment by lifeinchords** [comment]
this is very confusing and not intuitive. At the minimum plz add some statements like this in the docs

**Comment by ggcaponetto** [comment]
Maybe showing the imports in the samples could help!

**Comment by SinSarak** [comment]
import React from "react";

const DecorativeBox = () => {
  return (
    <div
      style={{
        height: "100%",
        backgroundColor: "var(--gray-a3)",
        backgroundClip: "padding-box",
        border: "1px solid var(--gray-a5)",
        borderRadius: "var(--radius-1)",
        backgroundImage:
          "url(data:image/svg+xml,%3Csvg width='6' height='6' viewBox='0 0 6 6' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='%239C92AC' fill-opacity='0.2' fill-rule='evenodd'%3E%3Cpath d='M5 0h1L0 6V5zM6 5v1H5z'/%3E%3C/g%3E%3C/svg%3E)",
      }}
    ></div>
  );
};

export default DecorativeBox;
