### ISSUE TITLE
Theme incorrectly rendering when used with NextJS

### ISSUE THREAD

**Issue by anthonysgro** [radix-ui/themes#180]
**Issue:**
Theme malfunctioning on render when used in NextJS project.

**Image:**
When using Theme wrapper:
<img width="1256" alt="Screenshot 2023-12-10 at 6 32 39 PM" src="https://github.com/radix-ui/themes/assets/64649626/16376091-a07c-4ac9-a54c-14a9f7a420de">

When not using Theme wrapper:
<img width="1249" alt="Screenshot 2023-12-10 at 6 33 48 PM" src="https://github.com/radix-ui/themes/assets/64649626/ea303c7d-6b25-48db-8382-ed666a243036">

**Repro:**
See my public repository here:
https://github.com/anthonysgro/venus

But basically all I did was run:
npx create-next-app@latest

Select yes for tailwind, typescript, an app router.

Then install @radix-ui/themes, and use the Theme component.

**Comment by kevinmitch14** [comment]
The repo you linked has nothing related to your Radix Themes setup. It would be very helpful if you include how you are setting it up.

You should look into the dark mode docs [here](https://www.radix-ui.com/themes/docs/theme/dark-mode). I would also delete the nextjs boilerplate CSS styles.

```tsx
// providers.tsx
"use client";

import { ThemeProvider } from "next-themes";

export function Providers({ children }: { children: React.ReactNode }) {
  return (
    <ThemeProvider attribute="class" disableTransitionOnChange>
      {children}
    </ThemeProvider>
  );
}
```

```jsx
// layout.tsx
<Providers>
  <Theme>
    {children}
  </Theme>
</Providers>
```

**Comment by anthonysgro** [comment]
Ah jeez, sorry i must have missed a commit. My layout.tsx looks like this:

```
return (
        <html lang="en">
            <Theme>
                {children}
            </Theme>
        </html>
```

**Comment by kevinmitch14** [comment]
You need to follow the [dark mode instructions](https://www.radix-ui.com/themes/docs/theme/dark-mode) for dark/light mode to work. Keep in mind `<Theme />` is light mode by default.

When using with the nextjs boilerplate project, there is css styling on the body, so the radix themes styling and globals.css styling are clashing.

<img width="552" alt="Screenshot 2023-12-11 at 01 22 32" src="https://github.com/radix-ui/themes/assets/55989505/dac7684f-a95c-4990-b666-c2897c7ceb74">
