### ISSUE TITLE
tw prop not applying the tailwinnd classes

### ISSUE THREAD

**Issue by AdityaKirad** [radix-ui/themes#182]
I'm using `@radix-ui/themes` with tailwind and here is my tailwind config
```ts
import { type Config } from "tailwindcss";
import { fontFamily } from "tailwindcss/defaultTheme";
import { radixThemePreset } from "radix-themes-tw";

export default {
  content: ["./src/**/*.tsx"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-lato)", ...fontFamily.sans],
        heading: ["var(--font-arvo)", ...fontFamily.sans],
      },
    },
  },
  plugins: [],
  presets: [radixThemePreset],
} satisfies Config;
```
I'm using the new experimental `tw` prop on `@radix-ui/themes` component to apply the tailwind classes on them but that doesn't work at all
![image](https://github.com/radix-ui/themes/assets/88867831/1e19350a-3263-4b0a-9717-d173408fd272)
![image](https://github.com/radix-ui/themes/assets/88867831/53508836-3a96-4e3b-a377-3fe1a9540e6d)
![image](https://github.com/radix-ui/themes/assets/88867831/ae2c951c-dd43-4a47-b801-c72f01d41f74)
![image](https://github.com/radix-ui/themes/assets/88867831/652350a9-e66a-46d6-ac7e-41f3f7210186)
![image](https://github.com/radix-ui/themes/assets/88867831/64fecad7-edb0-4694-9e87-3537acfd7194)

**Comment by reconsumeralization** [comment]
Make Sure the File is not in the Main directory "./src/**/*.tsx" 
Should be src/components/thecomponent.js

Could you please show your file structure?

**Comment by vladmoroz** [comment]
I have never heard of a `tw` prop. It's not something Radix Themes provides nor a Tailwind feature.
