### ISSUE TITLE
Dark theme stops being applied when children contain client-rendered context (NextJS 13)

### ISSUE THREAD

**Issue by georgiosd** [radix-ui/themes#19]
Hi! 

I was so excited by the release of the themes package that I thought I'd rewrite a small internal app in Next 13 with it and have some fun.

Here's the rub - this works:

```
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Theme appearance="dark" accentColor="red">
          <p>This will render dark</p>
        </Theme>
      </body>
    </html>
  )
}
```
This doesn't work (renders light theme):

```
'use client'

import React from 'react'

const TestContext = React.createContext(null)

export const ClientOnly = () => (
  <TestContext.Provider value={null}>
    <p>This is client only and renders light</p>
  </TestContext.Provider>
)

```

```
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Theme appearance="dark" accentColor="red">
          <ClientOnly />
        </Theme>
      </body>
    </html>
  )
}
```

Seems like a bug right?

**Comment by georgiosd** [comment]
I'm also noticing that the theme overrides the font imported by Next and there's no way to configure that??

**Comment by joaom00** [comment]
The docs has a section about [how to setup with next/fonts](https://www.radix-ui.com/themes/docs/theme/typography#with-nextfont)

**Comment by georgiosd** [comment]
Ok, thanks, but that's not the main issue. Why does the dark theme disappear in the second snippet?

**Comment by vladmoroz** [comment]
I used your code to create an example:
https://codesandbox.io/p/sandbox/twilight-firefly-h8q8j7

<img width="1624" alt="Screenshot 2023-08-14 at 11 18 39" src="https://github.com/radix-ui/themes/assets/8441036/80b62547-7785-4542-b9ca-dd30904a41b9">

Seems to work fine. Is the example accurate?

**Comment by jd-carroll** [comment]
This appears to be related to #22 

I think if that is solved, so will this issue

**Comment by jd-carroll** [comment]
@georgiosd See if [this comment](https://github.com/radix-ui/themes/issues/22#issuecomment-1680963676) describes your environment.

Specifically, look for the script tag that looks like: _(yours may be slightly different)_
```jsx
<script>
  !(function(){try{var d=document.documentElement,c=d.classList;c.remove('light','dark');d.style.colorScheme='dark';c.add('dark');}catch(e){}})();
</script>
```

Is it mounted directly under the `<body>` or is there a parent between the `<body>` and `<script>`?

**Comment by tobowers** [comment]
btw - I see this too but *only* in production, not in dev mode.

**Comment by georgiosd** [comment]
Sorry for the radio silence here, meant to provide an explicit repro but life has gotten in the way, still on my list.

I see the opposite however - fine in prod, dev is light theme only...
