### ISSUE TITLE
How to use css variables in themed primitives?

### ISSUE THREAD

**Issue by robhadfield** [radix-ui/themes#194]
I'm struggling to find documentation on how to use light/dark mode color variables with primitives.

I can change the theme OK using the `<Theme>` props - this adds the correct styles to any theme components, type, form elements etc.

In the docs for primitives the example styles use hard-coded color variables that do not update with the theme change.

For example in `<Popover>`...
```
.PopoverTrigger {
  background-color: white;
  color: var(--violet-11);
  box-shadow: 0 2px 10px var(--black-a7);
}
```

What is the recommended way to change these color variables so that they use the themed colors?

Any help appreciated! :)

**Comment by vladmoroz** [comment]
`var(--violet-11)` in light and dark mode does point to different values. Are you asking about using, say, `var(--violet-11)` in light mode, but `var(--green-5)` in dark mode?

**Comment by robhadfield** [comment]
Hey @vladmoroz - thanks for the response. maybe I didn't explain very well :) 

In this example (Link)[https://www.radix-ui.com/primitives/docs/components/popover]: 
<img width="406" alt="image" src="https://github.com/radix-ui/themes/assets/477344/89e19671-6a95-4580-a17d-39f42a4078d9">

The CSS provided sets the background as `background-color: white;`

What variables are available that could be used so that the background would be light in light mode and dark in dark mode.

Something like `var(--background-primary)` maybe? Is it somewhere in the docs do you know?

**Comment by vladmoroz** [comment]
Gotcha, and to clarify, is this about Radix Primitives (unstyled components) or is this about Radix Themes usage (a component library with pre-defined styles)?

**Comment by robhadfield** [comment]
The theme colors work fine for components included in the theme component library... it's when building a custom component (or primitive) where I want to use a theme-responsive color :)

**Comment by robhadfield** [comment]
I guess I'd expect color tokens something like...

```
.my-thing {
  background: var(--background-primary);
  color: var(--text-primary);
  
  &:hover {
    color: var(--color-link);
  }
}
```

I'm guessing they exist but I can't find them...

**Comment by vladmoroz** [comment]
I see, check out how Radix Themes colors are defined:
https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/styles/tokens/color.css

You’d normally use something like:
- `--color-background` and `--color-panel` for background colors
- `--accent-1` through `--accent-12` for your accent color
- `--gray-1` through `--gray-12` for grays
- Transparent variants of the above like `--gray-a5` or `--accent-a8` for components that need to blend with the background

More colors, like red, green, yellow, etc., are also available directly, see [Color docs](https://www.radix-ui.com/themes/docs/theme/color)

Will take a not to improve the docs for this area.
