### ISSUE TITLE
[Select] Issue

### ISSUE THREAD

**Issue by kimpoy31** [radix-ui/themes#199]
When using placeholder <Select.Trigger placeholder='Select Asignee..'/>

this error pops in console but the code works fine.

Type '{ placeholder: string; }' is not assignable to type 'IntrinsicAttributes & Omit<SelectTriggerProps, "ref"> & RefAttributes<HTMLButtonElement>'.
  Property 'placeholder' does not exist on type 'IntrinsicAttributes & Omit<SelectTriggerProps, "ref"> & RefAttributes<HTMLButtonElement>'.

**Comment by afiqakm** [comment]
I'm having the same issue as well.
