### ISSUE TITLE
[TextField] Issue

### ISSUE THREAD

**Issue by HarvindarPrv** [radix-ui/themes#201]
Unhandled Runtime Error
Error: Could not find the module "C:\Users\sjagj\OneDrive\Documents\GitHub\Next Js Project\NextJsApp\issue-tracker\issue-tracker\node_modules\@radix-ui\themes\dist\esm\components\text-field.js#TextField#Root" in the React Client Manifest. This is probably a bug in the React Server Components bundler.

**Comment by HarvindarPrv** [comment]
When I'm trying to import a text field it gives me this error and all the other components are working perfectly without any problem

**Comment by vladmoroz** [comment]
There are issues with React server components and parts used via dot notation (e.g. `TextField.Root`). Import the parts individually, e.g. `TextFieldRoot`, `TextFieldInput`, etc.

**Comment by HarvindarPrv** [comment]
Yeah, thank you so much it's working now.
