### ISSUE TITLE
[Dialog] Button seems to be invisible inside Dialog.Trigger

### ISSUE THREAD

**Issue by J-hta-n** [radix-ui/themes#204]
Hi all, as a macOS 14.1.2 user, whenever the`Button` component is nested inside the `Dialog.Trigger` component, it seems to become invisible as shown in the screenshot below (the outline of the button is shown with chrome's pesticide extension, but the main button cannot be seen).
<img width="100" src="https://github.com/radix-ui/themes/assets/103252521/d7614d93-d7d4-4a29-ba0e-0b8814e4ddf3)">

Shown below is the expected button.
<img width="100" alt="Screenshot 2023-12-22 at 10 56 06 PM" src="https://github.com/radix-ui/themes/assets/103252521/23afb81e-3e36-4981-b010-917af1be4b5e">

Below is the code snippet as provided in Radix UI's docs.
<img width="309" alt="Screenshot 2023-12-22 at 10 43 23 PM" src="https://github.com/radix-ui/themes/assets/103252521/63ecd249-9caa-456c-91e8-f2f58b9b9371">

I've tried modifying the radix UI button's props, and also haven't found an online solution to this yet. Does anyone know how this issue can be resolved? Thanks!

**Comment by kevinmitch14** [comment]
Do you have a reproducible example? Does the Button work as expected when used outside a Dialog?
