### ISSUE TITLE
[Feature request] Allow the `color` props on `Tabs`

### ISSUE THREAD

**Issue by pradel** [radix-ui/themes#205]
I want to be able to set my Tabs as `gray` and have the underline render the right color for example.

**Comment by vladmoroz** [comment]
Hey, that’s oversight on our part, we forgot to expose a prop for that. We’ll release a fix after the holidays, for now you can set a `data-accent-color="gray"` prop on the Tab List part as a workaround.

**Comment by kendallstrautman** [comment]
@pradel This was fixed in https://github.com/radix-ui/themes/pull/228 and will be included in the next release!
