### ISSUE TITLE
[Select] Issue

### ISSUE THREAD

**Issue by kimpoy31** [radix-ui/themes#207]
Unhandled Runtime Error
Error: A <Select.Item /> must have a value prop that is not an empty string. This is because the Select value can be set to an empty string to clear the selection and show the placeholder.

<Select.Content>
    <Select.Group>
              <Select.Label>Users</Select.Label>
              <Select.Item value="">Unassigned</Select.Item>
              {users?.map(user => 
                <Select.Item key={user.id} value={user.id}>
                  <Avatar src={user.image!} fallback="?" size={"1"} radius='full' />{" "}{user.name}
                </Select.Item>  
              )}
    </Select.Group>
</Select.Content>

I am trying to unassign select item with value "" (empty). In the documentation there seems to be no option to do so

**Comment by vladmoroz** [comment]
This is not a bug. As the error explains, Select Item can’t have `value=""`, however the Select itself can (e.g. as an initial value to show its `placeholder`).

If you need an item for the Unassigned user item, you’ll need to add a corresponding value that would represent it—e.g. `<Select.Item value="unassigned">Unassigned</Select.Item>`.
