### ISSUE TITLE
[Feature Request] Fluid `Button`, `TextArea` and `TextField`

### ISSUE THREAD

**Issue by Alex-Yakubovsky** [radix-ui/themes#21]
Hi,

I've been using `radix-ui` for what I'm building and really enjoying it! One issue I ran into is often times I want to have a full width button/input (particularly on mobile). I'd like to be able to do something like

```tsx
<Button fluid={{initial: true, md: false}}>...</Button>
```

I _can_ work around this by attaching a `css` class that sets the width or wrapping the `Button` in a `Flex` component but that feels needlessly awkward.

Happy to take a crack at implementing this.

**Comment by vladmoroz** [comment]
Hi Alex, with Radix Themes you are indeed supposed to use layout components like Flex to manipulate your layouts:

```jsx
<Flex direction="column" align={{ initial: 'stretch', md: 'start' }}>
  <Button>...</Button>
</Flex>
```

This is a bit more verbose, but off-loading layout responsibilities to these components makes the UI code easier to read and to maintain in the long run.

Aside from margin props on each component, we don’t plan to introduce other layout props on non-layout components.

**Comment by Alex-Yakubovsky** [comment]
Makes sense, thanks for sharing the reasoning!
