### ISSUE TITLE
Button inside alert dialog doesn't have color

### ISSUE THREAD

**Issue by bigxmark** [radix-ui/themes#210]
The color of the buttons inside of this Alert Dialog doesn't appear and it's only transparent **(to be specific, it doesn't appear in production, but appears fine in development)**

![image](https://github.com/radix-ui/themes/assets/127086054/22d3245b-64bb-49f2-bf59-461fc562c26c)
      
I tried several attributes to try to fix the button but it doesn't work.
One thing I know is it is hindered by this (I found it in the style section in devtools)

`[type=button], [type=reset], [type=submit], button {
    -webkit-appearance: button;
    background-color: transparent;
    background-image: none;
}`

I tried to delete this css element in the devtools style console and the color appeared, apparently the 

> background-color: transparent

 overrides the 

> background-color: red

 in the button.

**Comment by vladmoroz** [comment]
This style comes from the Tailwind reset. If you intend to use it, see this comment for solution:
https://github.com/radix-ui/themes/issues/109#issuecomment-1747345743
