### ISSUE TITLE
[`Dialog`] Content overflow when the parent is overflow

### ISSUE THREAD

**Issue by lamualfa** [radix-ui/themes#211]
If you have an overflow `body`, the `DialogContent` inside it will follow the `body`'s width and cause an overflow content.

# Overflow `body`

![photo_2023-12-29_12-05-15](https://github.com/radix-ui/themes/assets/39755201/016bc90b-8186-4f48-adf2-f7a676a11b08)

# Overflow `DialogContent`

![photo_2023-12-29_12-05-20](https://github.com/radix-ui/themes/assets/39755201/3bc47bd7-4ce5-46d0-9849-57ab98994136)

**Comment by vladmoroz** [comment]
I don't think that's the case, dialog uses position fixed which is set relative to the viewport. You are probably looking at a dialog that has content with intrinsic width and/or looking at it zoomed in.

Curious about the examples showcasing the WorkOS dashboard—are you trying to use it on mobile and running into issues or just testing?

**Comment by lamualfa** [comment]
> I don't think that's the case, dialog uses position fixed which is set relative to the viewport. You are probably looking at a dialog that has content with intrinsic width and/or looking at it zoomed in.

It should be like that. But for some reason, the Dialog issue only occurs on the WorkOS dashboard which has overflow content on its page like the **Organization / Settings** page.

> Curious about the examples showcasing the WorkOS dashboard—are you trying to use it on mobile and running into issues or just testing?

I rarely access the WorkOS dashboard via mobile honestly. I realized the issue after a quick try it on yesterday's trip to make a temporary account for my app. It's a bit annoying that I have trouble pressing the save button to close the Dialog.

**Comment by vladmoroz** [comment]
> I rarely access the WorkOS dashboard via mobile honestly. I realized the issue after a quick try it on yesterday's trip to make a temporary account for my app. It's a bit annoying that I have trouble pressing the save button to close the Dialog.

Gotcha, we have plans to improve mobile, good to have a data point like that, thanks.
