### ISSUE TITLE
<Select.Trigger> and <Select.Item> issue

### ISSUE THREAD

**Issue by bimal-saggu** [radix-ui/themes#212]
In <Select> component, we are unable to add a placeholder to <Select.Trigger> and set the value of <Select.Item> to an empty string.

**Comment by vladmoroz** [comment]
Could you give an example of what you are trying to achieve and the code you expected to work?

**Comment by bimal-saggu** [comment]
> Could you give an example of what you are trying to achieve and the code you expected to work?

I tried to fetch dynamic values (strings) from SQL database using a map function to the items of the Select component (<Select.Item>) by using the value property which can be displayed on the dropdown element when selected, it was a success. But, the moment we set the value property to null, it shows an error saying values cannot be empty string which was not the case in previous versions.
Coming to <Select.Trigger />, in the previous versions it consisted a property called placeholder which can be set as a default value, it doesn't exist in the latest version. 
Due to this issue, I downgraded radixui/themes to the older version for my personal project, it then worked. But, it still has a problem with the non-existence of placeholder property in the <Select.Trigger> element.

**Comment by vladmoroz** [comment]
Can you not render the items with empty values? I'm not sure I understand the problem otherwise.

If you need to display a placeholder, `Select.Root` may initially contain an empty `value`. However, individual items are always expected to hold a `value` that they represent.
