### ISSUE TITLE
[TextArea] Issue

### ISSUE THREAD

**Issue by sasicodes** [radix-ui/themes#215]
Border disappears on focus and out

Brave browser
[Version 1.61.109 Chromium: 120.0.6099.144 (Official Build) (arm64)]

https://github.com/radix-ui/themes/assets/29498872/a291f302-0d28-4849-b608-66f6201e87f3

**Comment by sasicodes** [comment]
Already created #167

**Comment by vladmoroz** [comment]
`TextArea` being hijacked by Grammarly is now fixed in a preview release, `2.1.0-rc.5`
