### ISSUE TITLE
[Badge] Issue

### ISSUE THREAD

**Issue by maxsilvauk** [radix-ui/themes#216]
For some reason I cannot get the badge to work in my project is there something I am doing wrong I am using Next14 and "@radix-ui/themes": "^2.0.3",

`import React, { FC } from 'react'
import { Badge } from '@radix-ui/themes'

import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/Table'

const CasesTable: FC = ({}) => {
  return (
    <>
      <Badge color='orange'>In progress</Badge>
      <Badge color='blue'>In review</Badge>
      <Badge color='green'>Complete</Badge>
      <Table>
        <TableCaption>Cases</TableCaption>
        <TableHeader>
          <TableRow>
            <TableHead>ID</TableHead>
            <TableHead>Date</TableHead>
            <TableHead>User ID</TableHead>
            <TableHead>Status</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>`

**Comment by vladmoroz** [comment]
Did you import the CSS and used the `Theme` provider component? (See [Getting started](https://www.radix-ui.com/themes/docs/overview/getting-started) guide). Otherwise, we'll need more info to help.
