### ISSUE TITLE
[<Select.Trigger>] Issue placeholder   

### ISSUE THREAD

**Issue by ishitvashukla** [radix-ui/themes#217]
"use client"
import { User } from "@prisma/client";
import { Select } from "@radix-ui/themes"
import axios from "axios";
import { useEffect, useState } from "react";

const AssigneeSelect = () => {
  const [users, setUsers] = useState<User[]>([]);

  useEffect(() => {
    const fetchUsers = async() => {
      const { data } = await axios.get<User[]>('/api/users');
      setUsers(data);
    }
    fetchUsers();
 
  }, [])
  return (
    <Select.Root >
          <Select.Trigger placeholder="Assignee..." />
          <Select.Content >
              <Select.Group>
              <Select.Label>
                   Suggestions
                  </Select.Label>
          {users.map(user =>
            <Select.Item
              key={user.id} value={user.id}>
              {user.name}
            </Select.Item>
          )}
              </Select.Group>
          </Select.Content>
              
          
    </Select.Root>
  )
}

export default AssigneeSelect;  

Type '{ placeholder: string; }' is not assignable to type 'IntrinsicAttributes & Omit<SelectTriggerProps, "ref"> & RefAttributes<HTMLButtonElement>'.
  Property 'placeholder' does not exist on type 'IntrinsicAttributes & Omit<SelectTriggerProps, "ref"> & RefAttributes<HTMLButtonElement>'.ts(2322)
(property) placeholder: string        

getting this error in my editor

**Comment by vladmoroz** [comment]
This was fixed in 2.0.3, please update to the latest version.
