### ISSUE TITLE
Switch Component rendering as a dot on the screen

### ISSUE THREAD

**Issue by alvinokafor** [radix-ui/themes#220]
```
 <Switch
      checked={recurrentPayment}
      onClick={() => setRecurrentPayment(!recurrentPayment)}
  />
```

I am simply trying to render the switch component from radix themes to control state for an option.  But the component renders as just a dot on the screen. See below for screenshot.

![image](https://github.com/radix-ui/themes/assets/60660504/1cc9b463-01c1-449d-a559-22b9d83f26a7)

To Note: It only renders this way when I use it inside the Dialog Component. It renders just fine on other components.

The project which I am using it is a Next 14.0.3 project.

Any help on this issue will be appreciated, thanks.

**Comment by vladmoroz** [comment]
Any chance this happens in a custom dialog component and not a Radix Themes dialog? Otherwise would need a reproduction example on something like CodeSandbox to look into it.
