### ISSUE TITLE
[Button] Issue

### ISSUE THREAD

**Issue by abilovelchin** [radix-ui/themes#246]
Why type of cursor of mouse is not pointer? Is there any reason or just have been forgotten?!

**Comment by benoitgrelard** [comment]
There is a reason, pointer should be reserved to links as it's an affordance that helps user figure out if they are about to navigate away, etc.

That being said, we realise that this is somewhat of a controversial topic, so we allow users to customise the cursor behaviour:

You can add a style that overrides these variables on the .radix-themes selector:
https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/styles/tokens/cursor.css
