### ISSUE TITLE
[Tabs] Tab trigger not compatible for HTML form navigation

### ISSUE THREAD

**Issue by aem** [radix-ui/themes#250]
Today, a radix `Tabs` element renders each tab `Trigger` as an HTML `button`, but the `value` prop is not passed down to the rendered button. In a traditional HTML form, if each child has the same `name` and differing `value`s, clicking each button will set a query param for `name={value}`, but since Radix stops the `value` from propagating this behavior is impossible. This removes the ability to use a simple HTML form for navigation and URL state. 

Would it be possible to optionally pass the `value` prop to the underlying button, allowing the use of an HTML form to preserve the tab state in the URL? 

[This codesandbox](https://codesandbox.io/p/sandbox/radix-form-repro-x3tw45?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrpi1j5200062e69bmpc4cdg%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrpi1j5200022e69s0iaz4r6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrpi1j5200032e694xn23egv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrpi1j5200052e69v74nks2p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrpi1j5200022e69s0iaz4r6%2522%253A%257B%2522id%2522%253A%2522clrpi1j5200022e69s0iaz4r6%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clrpi1j5200052e69v74nks2p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrpi1j5200042e69ae78nfke%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%253Fthing%253Done%2522%257D%255D%252C%2522id%2522%253A%2522clrpi1j5200052e69v74nks2p%2522%252C%2522activeTabId%2522%253A%2522clrpi1j5200042e69ae78nfke%2522%257D%252C%2522clrpi1j5200032e694xn23egv%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrpi1j5200032e694xn23egv%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) demonstrates the behavior difference between plain HTML buttons and the buttons Radix Tabs render

**Comment by vladmoroz** [comment]
Tabs for navigation are coming soon:
https://github.com/radix-ui/themes/pull/248

This will be a much easier way to achieve the outcome you are describing

**Comment by vladmoroz** [comment]
No target date yet, but we will probably do a release candidate this week that you will be able to use

**Comment by aem** [comment]
Great to hear, I'll keep an eye out for it! Thanks again

**Comment by vladmoroz** [comment]
@aem `TabNav` is now available in a preview release, `2.1.0-rc.5`

**Comment by aem** [comment]
Much simpler, works great!!
