### ISSUE TITLE
[Popover] Scroll content into view does not work

### ISSUE THREAD

**Issue by wilcoschoneveld** [radix-ui/themes#268]
Context:
we are using a radix popover with long content and in a e2e test we would like to scroll towards a button in the bottom of the popover

Problem:
using `element.scrollIntoView()` does not work

Reproduction:
can be reproduced in the radix popover doc, see gif:
![screencap-popover-scroll-into-view](https://github.com/radix-ui/themes/assets/3064588/94d8bfb1-cb3c-4f84-944c-865a9ef05b5e)

**Comment by vladmoroz** [comment]
I don't think that realistically we'll be able to address this—this seems to be just a quirk of how `scrollIntoView()` works with `position: fixed `, and there's already a lot of constraints to make the positioning work.
