### ISSUE TITLE
Runtime error when using addChild on Tabs trigger

### ISSUE THREAD

**Issue by penx** [radix-ui/themes#269]
Say I have an app, where tabs link to different routes (or query string changes), and I:

- want users to be able to right click and open tabs in a new window (but keep radix behaviour with a preventDefault when not opening in a new window)
- improve SEO for these pages by ensuring links to them are picked up by a crawler

Then it's reasonable to want to configure the tabs component so that each tab is an anchor with an href instead of a button element.

Tabs trigger has an asChild prop which indicates this should be possible, however when it is used like this:

```tsx
<RadixThemes.Tabs.Trigger value={view} asChild>
  <a href={`?${urlParams.toString()}`} onClick={(e) => e.preventDefault()}>
    Some Tab
  </a>
</RadixThemes.Tabs.Trigger>
```

Then I get a runtime error:

```console
Unhandled Runtime Error
Error: React.Children.only expected to receive a single React element child.
```

I think this is related the tabs trigger's children being duplicated to create rt-TabsTriggerInner and rt-TabsTriggerInnerHidden.

I have tried wrapping the children inside an anchor, without using asChild, which works but the click area for the link is smaller than the tab button (with hover effect) which is not ideal.

**Comment by penx** [comment]
Awesome, thanks!

Do the docs or playground for release candidates get published anywhere?

**Comment by benoitgrelard** [comment]
No docs yet no, we'll update the docs when we release the public version.
