### ISSUE TITLE
Ignores some Tailwind classes while accepting others

### ISSUE THREAD

**Issue by cwwmbm** [radix-ui/themes#27]
Namely, I wanted to use hover:bg-gray-200 (or any other bg color) class from Tailwind on the Card component to highlight the card mouse hovers over among many other cards, and it absolutely ignores it.

hover:cursor-pointer works just fine. I had to resort to force-injecting style via CSS file, and even then it only worked once I used !important tag:

.card-hover:hover {
    background-image: #cacaca !important;
}

It still didn't work without the !important flag.

**Comment by jd-carroll** [comment]
Could you put together a codesandbox example?

I am also using themes + tailwind and it is working great!

**Comment by kevinmitch14** [comment]
Could be helpful: #16 

<img width="463" alt="Screen Shot 2023-08-18 at 13 06 41" src="https://github.com/radix-ui/themes/assets/55989505/9c7ebd25-af07-4189-84cf-4227535ece92">

**Comment by vladmoroz** [comment]
You can use Tailwind’s [important modifier](https://tailwindcss.com/docs/configuration#important-modifier), e.g. `hover:!bg-gray-200` to strong-hand any CSS.

That said—if you can't achieve the customisation that you need by tweaking the theme variables and just need custom styles on the components, you are probably better off creating a quick component yourself. It’s easier and more maintainable than fighting the built-in styles. The point of Radix Themes is to build apps faster by skipping a lot of styling and design choices. If you want different design choices for a particular component, creating your own version is always safer.
