### ISSUE TITLE
TextField.Input styling

### ISSUE THREAD

**Issue by twirlse** [radix-ui/themes#28]
I'm trying to style the TextField.Input and it's a bit impossible to do right now because there is an extra ```<div class="rt-TextFieldChrome">``` rendered in markup that contains real styling, and the className from Input component is not applied to it.
Not really sure why this div exists, but it would be nice to be able to customize the component by adding classes to Input's className.

**Comment by vladmoroz** [comment]
Hi @twirlse, it's set up like this to make auto-sized textfield slots possible. What kind of customisation do you have in mind?
