### ISSUE TITLE
compatibility with tailwind

### ISSUE THREAD

**Issue by faithfulojebiyi** [radix-ui/themes#3]
How compatible is this with tailwind css

**Comment by viktorbonino** [comment]
For now you need to write your own preset/plugin or extend the tailwind config with radix themes variables.
I’m working on a preset/plugin that you can install through npm.

**Comment by triptu** [comment]
Thanks @viktorbonino for publishing the [preset](https://twitter.com/ViktorB01/status/1689321621952110615). [Repo Link](https://github.com/viktorbonino/radix-themes-tw)

**Comment by vladmoroz** [comment]
Radix Themes is compatible Tailwind CSS, but as @viktorbonino said, you’ll want to extend your config with our variables.

If your plan is to use Tailwind just for its layout utilities, make sure to also check out the layout components that Radix Themes provides as they cover similar responsibilities.
