### ISSUE TITLE
[Button] - Can we add cursor pointer 

### ISSUE THREAD

**Issue by LanguageXange** [radix-ui/themes#309]
I'm using radix-ui ( first time using it ) with tailwind css, and the `cursor-pointer` className won't work

```
  <Button className="cursor-pointer">
          Submit 
    </Button>
```

And I had to use `style` to simply add a pointer cursor

```
  <Button style={{ cursor: "pointer" }}>
          Submit 
        </Button>

```

I wonder if we could add a `cursor` prop to Button and make `pointer` the default ?

e.g. `<Button cursor="xxx" >`

**Comment by vladmoroz** [comment]
You'll need to update your Tailwind setup to make sure the utility classes work. As for cursors, there's a more native way to set it up across the board for all components.

Please see this comment:
https://github.com/radix-ui/themes/issues/123#issuecomment-1778862252
