### ISSUE TITLE
Question: Are you planning to introduce loading indicators and lists?

### ISSUE THREAD

**Issue by ctkc** [radix-ui/themes#31]
Hello,

Thank you for this library! I really like it and I'm planning to use it on production.

I was wondering if you are planning to include loading indicator components such as spinners, bars and skeletons. On the other hand, the only way to create some sort of list currently is through the `Table` component, I was also wondering if you are going to incorporate list components (`ul` and `ol`)

Thank you!

**Comment by Andrii-Antoniuk** [comment]
I'd like to see loaders too!
And I'm willing to contribute to that as well

**Comment by vladmoroz** [comment]
Loading components are coming in the next few weeks. What design did you have in mind for lists?

**Comment by Andrii-Antoniuk** [comment]
Let's split this up into 2 requests, perhaps 😅
Since it is quite confusing to have them on the same page.

About listing functionality - I think that some default styling params, such as removing or adding the circle for  ul`s and font size is enough.
But honestly - sounds like an overkill 😅

**Comment by vladmoroz** [comment]
Ah, OK, so you are basically interested in a text list that you could use alongside a paragraph?

**Comment by Andrii-Antoniuk** [comment]
Let's get the @ctkc idea here too, since that's just my thought, and he was the one who really requested/asked for this feature :)

**Comment by ctkc** [comment]
@vladmoroz I think @Andrii-Antoniuk proposal is enough for now, we can start with something simple like that and add more on top of it. I know we could create a list with `Flex` but I think is good to have the list elements available for semantic reasons as well.

**Comment by vladmoroz** [comment]
We introduced a couple of loading components in 3.0; see the [announcement](https://www.radix-ui.com/blog/themes-3) and the [changelog](https://www.radix-ui.com/themes/docs/overview/releases#300)
