### ISSUE TITLE
Feature suggestion - Add responsive display property to TabNav Link

### ISSUE THREAD

**Issue by penx** [radix-ui/themes#314]
Say I have a TabNav with 8 items:

- Home
- Tasks
- (... some other things)
- Account

but on low breakpoints I want to reduce the tabs to:

- [Hamburger Icon]
- Account

...making the hamburger icon tab trigger a dropdown containing Tasks and "some other things".

I could do this with the TabNav if TabNav items had the display property.

Does this make sense? If so are you able to add the display property to TabNav Link?

🙏

**Comment by penx** [comment]
Actually I could probably do this by wrapping the items:


```tsx
<RadixThemes.Flex
    display={{ initial: "none", md: "flex" }}
    asChild
  >
    <RadixThemes.TabNav.Link
      asChild
      active={pathname.startsWith("/home")}
    >

```

**Comment by benoitgrelard** [comment]
I was going to suggest your workaround, considering:
- that this is not a hugely common scenario
- that we want to keep the APIs lean
- that we want to keep layout concerns to layout components

I think this is the right approach.

**Comment by benoitgrelard** [comment]
Looks cool!

The only thing I'd say that I would do differently would be to completely hide when `TabNavRoot` using (an `asChild` layout component like you do) and replace with a nav with the dropdown instead.

I understand you're probably trying to take advantage of "some" of the styling there already, but I don't think you end up with what you expect anyway, like making the trigger a tabnavlink doesn't make it navigable with the keyboard, etc

**Comment by penx** [comment]
> I understand you're probably trying to take advantage of "some" of the styling there already

yes in this example the mobile nav is really just using TabNav for the consistent bottom border, but perhaps better to swap the whole thing out. 

I’m not sure tab items or tab nav items were designed to allow for a single icon as their children. I guess not. I have 3 different approaches here. 

I could imagine still keeping one or two items on mobile, and putting the rest under the hamburger. 

Definitely feels I’m doing a lot here that isn’t intentional usage though, so thanks for the tip re: keyboard access.
