### ISSUE TITLE
[Select] Issue tailwindcss className is not working.

### ISSUE THREAD

**Issue by alicefromkr** [radix-ui/themes#321]
I am using 

- Next 14.1.0
- radix-ui/themes 2.0.3
- tailwindcss 3.3.0

Seems like className does not work inside select.root.

![image](https://github.com/radix-ui/themes/assets/30956835/9457525a-4b3d-4190-a87b-53a9137fb591)

I want to give select.root a min width. Is there a way I can achieve this?

**Comment by vladmoroz** [comment]
You want to put a class on the Trigger element, because the Root part doesn't render any HTML.
