### ISSUE TITLE
docs not update for last release Add width props to portalled components

### ISSUE THREAD

**Issue by faithfulojebiyi** [radix-ui/themes#324]
<img width="789" alt="Screenshot 2024-02-29 at 06 12 53" src="https://github.com/radix-ui/themes/assets/26503966/da967629-d830-4ac7-aee2-fb3b0d3bd705">

No example showing how to use the width props

**Comment by vladmoroz** [comment]
It's not in a stable release yet. We will update the docs when a stable 3.0 is out.
