### ISSUE TITLE
[Select] Issue layout shift, SSR

### ISSUE THREAD

**Issue by llezhava** [radix-ui/themes#329]
Hello everyone!

Nice work, I like your library a lot.

I have a layout shift issue with the Select component during server-side rendering. Value is preselected from the beginning, so theoretically, there must be no issues.

Here is link to reproduction: https://stackblitz.com/edit/remix-run-remix-jjnr3m?file=app%2Froutes%2F_index.tsx

**Comment by benoitgrelard** [comment]
@vladmoroz I believe for this one to be fixable in Radix Themes, we need to ensure we pass `children` to the underlying `Select.Value` from the primitive. This is essentially because the only way for it to have the correct value server side, is to control it into the trigger value yourself (as per https://www.radix-ui.com/primitives/docs/components/select#controlling-the-value-displayed-in-the-trigger).

**Comment by vladmoroz** [comment]
Fixed, this is available in [3.0.0-rc.14-patch.1](https://www.npmjs.com/package/@radix-ui/themes/v/3.0.0-rc.14-patch.1)

**Comment by vladmoroz** [comment]
You'll need to pass the text you want to render in the Trigger yourself though (see https://www.radix-ui.com/primitives/docs/components/select#controlling-the-value-displayed-in-the-trigger)

**Comment by dawi** [comment]
I have one question regarding this issue.

Passing the text to render to the trigger like this works well:

```jsx
<Select.Trigger>
    {value}
</Select.Trigger>
```

However I cannot use the following approach:

```jsx
<Select.Trigger>
    <Select.Value aria-label={value}>
        {countries[value]}
    </Select.Value>
    <Select.Icon />
</Select.Trigger>
```

Because ```Select.Value``` is not exported from ```@radix-ui/themes```.

**Comment by vladmoroz** [comment]
@dawi what is the problem exactly?

**Comment by dawi** [comment]
@vladmoroz I don't need value and icon parts. It just was not clear to me if

```
<Select.Trigger>
    {value}
</Select.Trigger>
```

is the right thing to do.

**Comment by vladmoroz** [comment]
Yep it is, we'll document it @dawi

**Comment by llezhava** [comment]
> You'll need to pass the text you want to render in the Trigger yourself though (see https://www.radix-ui.com/primitives/docs/components/select#controlling-the-value-displayed-in-the-trigger)

thank you!
