### ISSUE TITLE
Webpack throws DeprecationWarning 

### ISSUE THREAD

**Issue by heliokthonos** [radix-ui/themes#330]
**Environment Information**:
```
Operating System:
  Platform: linux
  Arch: x64
  Version: #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2
Binaries:
  Node: 20.11.1
  npm: 10.5.0
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 14.1.1
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

I am using Next 14.1.1 and when I am trying to build the application the applied global styling throws an error: 
`[DEP_WEBPACK_MODULE_UPDATE_HASH] DeprecationWarning: Module.updateHash: Use new ChunkGraph API`
Therefore when I am looking at the application in development build it looks like this:
![image](https://github.com/radix-ui/themes/assets/26341681/03df5c8d-1799-4d1a-b60e-4e120624d901)
And when looking at it in production build:
![image](https://github.com/radix-ui/themes/assets/26341681/ea306d0b-ac9f-45d9-833f-29169fb9d7ff)

**Comment by vladmoroz** [comment]
> [DEP_WEBPACK_MODULE_UPDATE_HASH] DeprecationWarning: Module.updateHash: Use new ChunkGraph API

This is unrelated to Radix Themes.

***

As for the visual differences between dev and prod build, do you have Tailwind in that app?

**Comment by heliokthonos** [comment]
Yes I have tailwind installed.

**Comment by vladmoroz** [comment]
This style comes from the Tailwind reset. If you intend to use it, see this comment for solution:
https://github.com/radix-ui/themes/issues/109#issuecomment-1747345743

If not, just uninstall it.
