### ISSUE TITLE
Expand <Box as="..." /> Support

### ISSUE THREAD

**Issue by jd-carroll** [radix-ui/themes#332]
The next version of Radix (🎊) updates `Box` to support `as`. However, it restricts the `as`'d component to be either `div` or `span`. 

Therefore, if I am using `NextLink` (i.e. `import NextLink from 'next/link';`), **I cannot do the following**:
```jsx
<Box as={NextLink} href={linkToPath}>
  <MyLogo/>
</Box>
```

But I can do this:
```tsx
<Box asChild>
  <NextLink href={linkToPath}>
    <MyLogo />
  </NextLink>
</Box
```

Beyond that `Box` would not presently know about the `href` prop, is there any other reason why this is not allowed?

**Comment by vladmoroz** [comment]
This is by design, `as` is meant to only provide access to common tags that make sense for a particular component. Otherwise just use `asChild`. Polymorphic types tend to be slow and buggy, so we are not planning to implement that.
