### ISSUE TITLE
remix-vite with themes@next suffrers serving allow list problem

### ISSUE THREAD

**Issue by GOWxx** [radix-ui/themes#334]
When using a basic remix-vite project with themes@next added, you may encounter prompts such as

```bash
The request url "[EDITED]/node_modules/.pnpm/@radix-ui+themes@3.0.0-rc.13-patch.1_@types+react-dom@18.2.19_@types+react@18.2.61_react-dom@18.2.0_react@18.2.0/node_modules/@radix-ui/themes/styles.css" is outside of Vite serving allow list.
```

I prepared a repository for reproduction. 
repository link: https://github.com/GOWxx/solve-remix-vite-add-radix-ui-themes-allow-list-problem
The steps are simple: 
1. pull down the repository 
2. run it 
3. see the prompt in the terminal.

I'm not sure if this is an issue with remix-vite or themes@next, but it might be helpful for the development of themes@next. So I came to this issues page hoping to get some help. Thank you all!

**Comment by GOWxx** [comment]
Confirmed that the issue was caused by the default template update of remiv-vite.

**Comment by vladmoroz** [comment]
@GOWxx what was the fix? I'm not a vite expert, so would be good to learn in case anyone asks here

**Comment by GOWxx** [comment]
Actually, there isn't a problem, but the remix-vite template has enabled a configuration as mentioned in https://github.com/remix-run/remix/issues/8967#issuecomment-1975928826. The content of the configuration is:

```
  server: {
    fs: {
      allow: ["app"],
    },
  },
```

The documentation for this configuration is at: https://vitejs.dev/config/server-options#server-fs-allow. It states:

Restrict files that could be served via `/@fs/`. When `server.fs.strict` is set to `true`, accessing files outside this directory list that aren't imported from an allowed file will result in a `403`.

This means that after enabling this configuration, you will indeed get a prompt in the terminal:
`The request url "..." is outside of Vite serving allow list.`

I'm not a Vite expert too, so this is all the information I can provide. 
I also don't have the energy to figure out a better configuration at the moment,

but I can offer two possible solutions:

One is to remove this configuration:

```diff
  server: {
    fs: {
-     allow: ["app"],
    },
  },
```

The other is to add [server-fs-strict config](https://vitejs.dev/config/server-options#server-fs-strict) `server.fs.strict: false`:

```diff
  server: {
    fs: {
      allow: ["app"],
+     strict: false
    },
  },
```

I'm not sure which method is better, or if there's a better way. I'm also looking forward to a Vite expert who can explain this clearly.

I'm thinking that, ideally, even if the path for `fs.allow` is set to `'app'`, since my components are already being used by files within the app directory, Vite should have the capability to automatically handle the related information. However, I'm not sure why it isn't doing so. It could be an issue with Vite or perhaps the way I'm using it. I hope to have the time to figure this out later.

**Comment by vladmoroz** [comment]
Makes sense, thank you @GOWxx

**Comment by GOWxx** [comment]
update:

the config `server.fs.allow` is deleted from remix-vite templates.

https://github.com/remix-run/remix/pull/8972
