### ISSUE TITLE
[Feature Request] Add `loading` boolean prop to all buttons. Render Spinner and disable the button when `loading` is true

### ISSUE THREAD

**Issue by snelsi** [radix-ui/themes#348]
## Background

Launching an async action on a button click is a very common pattern. For example, submitting forms or running post/put/delete requests to your DB. While the action is pending, it's usually a good UX practice to disable the button and show some sort of Spinner / Loader to indicate that something is going on in the background.

At the moment, Radix Themes doesn't have a built-in way to show a loading indicator while the action is pending. I think it can be a very useful addition to the library.

![image](https://github.com/radix-ui/themes/assets/15171036/c47aac44-b10a-40ec-b8a9-db092c3c9b70)

## Examples:

https://mui.com/material-ui/api/loading-button/
https://uxmovement.com/buttons/when-you-need-to-show-a-buttons-loading-state/
https://coreui.io/bootstrap/docs/components/loading-buttons/

## Possible implementation:

Taken from [MUI LoadingButton API](https://mui.com/material-ui/api/loading-button/):

<img width="815" alt="Снимок экрана 2024-03-08 в 17 04 09" src="https://github.com/radix-ui/themes/assets/15171036/9476ea06-6a34-4010-bcce-3c16d672c185">

## Usage examples:

Form submit:
```tsx
const { mutate, isPending } = useMutation();

return (
  <form onSubmit={mutate}>
    <input name="message" />
    <Button
      type="submit"
      // Disable button and show loading indicator while form submit is pending
      loading={isPending}
    >
      Submit
    </Button>
  </form>
)
```

Async action:
```tsx
const { mutate, isPending } = useMutation();

return (
    <Button
      onClick={() => mutate(id)}
      // Disable button and show loading indicator while mutation is pending
      loading={isPending}
    >
      Delete profile
    </Button>
)
```

**Comment by kevinmitch14** [comment]
This will be possible in v3! You can use it now in the rc version.

**Comment by snelsi** [comment]
Oh, cool! Didn't know that it's already implemented in the rc. 😅
I guess this ticket is redundant then

**Comment by kevinmitch14** [comment]
Here is initial PR - https://github.com/radix-ui/themes/pull/203
