### ISSUE TITLE
DecorativeBox issue

### ISSUE THREAD

**Issue by atulyakr** [radix-ui/themes#359]
In the box, grid and flex component this decorative tag is used a lot in the documentation. But when I implement it on my local computer it gives an error that the decorative box is not defined. Please provide a solution for this as soon as possible.

**Comment by kevinmitch14** [comment]
See https://github.com/radix-ui/themes/issues/179

**Comment by vladmoroz** [comment]
> Please provide a solution for this as soon as possible.

What's the urgency?

**Comment by 6qat** [comment]
Is the DecorativeBox component source code available?

**Comment by SinSarak** [comment]
import React from "react";

const DecorativeBox = () => {
  return (
    <div
      style={{
        height: "100%",
        backgroundColor: "var(--gray-a3)",
        backgroundClip: "padding-box",
        border: "1px solid var(--gray-a5)",
        borderRadius: "var(--radius-1)",
        backgroundImage:
          "url(data:image/svg+xml,%3Csvg width='6' height='6' viewBox='0 0 6 6' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='%239C92AC' fill-opacity='0.2' fill-rule='evenodd'%3E%3Cpath d='M5 0h1L0 6V5zM6 5v1H5z'/%3E%3C/g%3E%3C/svg%3E)",
      }}
    ></div>
  );
};

export default DecorativeBox;
