### ISSUE TITLE
DecorativeBox Issue

### ISSUE THREAD

**Issue by dhoegl** [radix-ui/themes#372]
Looking for info on how to define DecorativeBox - documentation is unclear.

**Comment by vladmoroz** [comment]
You'll have to implement it yourself, here’s a reference:
https://github.com/radix-ui/website/blob/53375672001048f15505f533d0ec5c6fe24996c3/components/ThemesDocsAssets.tsx#L755

Why do you need it? It's just a presentational component in the docs not meant to be used in a real app

**Comment by singlefabric** [comment]
import * as React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { cn } from '@/lib/utils'; // Optional utility for className merging

interface DecorativeBoxProps extends React.HTMLAttributes<HTMLDivElement> {
  asChild?: boolean;
}

const svgBackground = `url("data:image/svg+xml,%3Csvg width='6' height='6' viewBox='0 0 6 6' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='%239C92AC' fill-opacity='0.2' fill-rule='evenodd'%3E%3Cpath d='M5 0h1L0 6V5zM6 5v1H5z'/%3E%3C/g%3E%3C/svg%3E")`;

const DecorativeBox = React.forwardRef<HTMLDivElement, DecorativeBoxProps>(
  ({ asChild = false, className, style, ...props }, ref) => {
    const Comp = asChild ? Slot : 'div';
    return (
      <Comp
        ref={ref}
        className={cn(
          'rounded-sm border',
          'border-gray-300',
          'bg-[var(--gray-a3)]',
          className
        )}
        style={{
          height: '100%',
          backgroundClip: 'padding-box',
          backgroundImage: svgBackground,
          ...style,
        }}
        {...props}
      />
    );
  }
);
DecorativeBox.displayName = 'DecorativeBox';

export default DecorativeBox;
