### ISSUE TITLE
Suggestion - Improved DX for fieldset

### ISSUE THREAD

**Issue by penx** [radix-ui/themes#378]
At the moment, if I want markup a Section, Flex or Box as a fieldset element without inheriting user agent fieldset styles I need three components:

```tsx
<RadixThemes.Section asChild>
  <RadixThemes.Reset>
    <fieldset>
```

Would it be possible to support one of the following for the same effect? It would reduce a lot of noise in some pages without having to create my own component for handling this.

```tsx
<RadixThemes.Section as="fieldset">
```

```tsx
<RadixThemes.Section asChild>
    <fieldset>  {/*auto reset by Section, Box or Flex */}
```

This is just something minor I thought of during development of a large form page. I have no problem with you closing if you're not sure it's valuable  :)

**Comment by vladmoroz** [comment]
It's not a canonical example of how we'd expect Section to be used (nothing wrong with that though), nor inline with how we think about resets, so we wouldn't plan to work on it.

Sounds like you might want to just abstract it into your own fieldset component?

We had some plans for providing our own fieldset element in this release, but had to back out for now because of a lot of unexpected complexity in this area. Good to see though that this seems to be a somewhat common need.

**Comment by penx** [comment]
ok thanks, yes a Fieldset component is probably going to be a better end result, good to know it's being considered

**Comment by vladmoroz** [comment]
What does your UI look like in this case?

**Comment by penx** [comment]
I've [made an example here](https://penx.github.io/radix-themes-playroom/#?code=N4Igxg9gJgpiBcIA8BhCA7ALgQwJbpgCcACAWwA8BeAHRABZaA%2Ba9Y4pAZRjE1w2IDOuAF4waIAExMWbNkgBCEcsWwCUAC1wAbKM1ay5AJRgCYmPQYNIAZrhg7T5mZasAJGNij4A5irWadQRExWgYQCxdLJGNHCMiorRhvGHRdLkxedF8ARiQAekTk1Lj49jyYsxKXfPdPHz1neKQAFRhyTDIAT3EpED9xAAdaINEe6X1S4gBmYkI6iAEVQhhiAFdTKAAaQQhiAHcV0mxCAGtVgeJMTUXTHj5WVRViW3soRwA6RtKAClpDeeIACNVhl%2BN5CBBzgJgMNaABfL5NAAy%2BBOxHUy2s4nUGQGAngeTye2J7z2U3eEEI3jyAHUAIIASTymBBlNw2C0Ajy1kppC54MhAx8eQAxHMvBAALTA0HoATjSYGATqSGBDl7bCdRaAlYC84wKBrIRZZ52BxmT4TUr5FHoE5VSK0ACUiKieVa7QaVuq-wlKGOUAA4hDzu9DBAIB1NN51GgsHMBB1YNZsKstJgAGoc1YhEAQazWBWK6Lzf2EIMhgbvBmYGCkRh0-K%2BvhliuC6u1%2Buun2lgPB9s1uuMeRN3vl-uhwdd72REt%2BvuVjtDlCj%2BfjxdTh1Wcpjtuh8ORrdlF7mpwzpsmSpffKKcgRfJcO4YL1yR%2B8fhCUa0Xp%2BDTaXTXhUZ7VCebxXjOci1F4JqfrmYSMOkmS%2BBINQeNB3hHi0bQdKQ3TfsMqiDMMsFjOE3ayIhPjEBI6KPKQaa8AMiSzPY2C1oaoECO8xA0isABuHK4FAbErFcdaXBAyRiSQqjkWwAlaEJbH3LMaYmEsKz4LW5YwAMKSwFg3G8fscwXGJpDEPgTycRa5H5B6wGzreXTiPBcnsA5-S0Fo2A6lowykICpEjLmvRHgYdKkJCWDufZ2HhewHCKbAJDJqm6ZZloOaUMAADaACsAAMAC6cLEHkmF5LemFAQlNhmmBjmTFh7ReSAQx9CR%2BF9Kof46AlVi1e51SFPpA2RAA8gQxD5pc6grJxlmLPR6a4ExKxgPNYAnICSgmNsAi7AcKickdpnDZEYmmJZDymq8jjbAQiYGvsuBXFZYnEAMxwpB0NmYJaipuqNxQXXI5SXk11ruvFF2oFtO1KK2E5VgeUa4DGcaYAmOGYK5RZA-D3CI%2BQyMbp2jAAGIeCyyzEI2eQaMTu2kwuA4U2D7BM9tLNk%2BzQ7U2xqx0yOjMI7zbOThzEGztzJN81LAs08LKwrmLzNI5LVabpzRM85r678-Wgu0ysAAi%2BRyxLhuK9OhPq-rrM26jEZQ9U3INbEdkQ1754e-d4HbkN%2BgPtw77oC%2BiVhypXWSAT7DVa6SBQVRsfwZRJpTKhdRZA6LU4Xhcc9QIRGdcEpFHs01xLU8xreMxoEHbs6C7P9NfrAagNug5ecOXSyzYOVvfYS53VtR1IXBYJ3joOIhAYzi8cGAAou0%2BkvfNWhmdhXfbj315VUo955G%2B9x6JbGA4PgRB6CAcJAA).

This is pretty much like our UI looks like, though I've replaced the text with an explanation of the markup.
