### ISSUE TITLE
Text: `Types of property 'as' are incompatible.`

### ISSUE THREAD

**Issue by kevinmitch14** [radix-ui/themes#390]
Doing something like the following will result in TS errors.
> Type '"span"' is not assignable to type 'undefined'.
> Types of property 'as' are incompatible.

```tsx
function BreadcrumbText({
  children,
  ...props
}: React.ComponentPropsWithoutRef<typeof Text>) {
  return (
    <Text
      color="gray"
      size={"2"}
      as={"span"}
      className="max-w-[17ch] truncate"
      {...props}
    >
      {children}
    </Text>
  );
}
```

Is this expected? And if so, what is the recommenced way to extend `<Text />`? In this case I want to text to be a span by default, with the options to override. 

```tsx
// This also does not work
{
  children,
  as = "span",
  ...props
}
...
<Text as={as} {...props} />
```

**Comment by vladmoroz** [comment]
We'll probably want to document this, but essentially TypeScript freaks out that you might pass `asChild={true}` in the props, which is incompatible with the `as` prop.

If you don't need the option to `asChild` this component, just add `asChild={false}` below your props spread so that it knows that `asChild` won't be set.

```
function BreadcrumbText({
  children,
  ...props
}: React.ComponentPropsWithoutRef<typeof Text>) {
  return (
    <Text
      color="gray"
      size={"2"}
      as={"span"}
      className="max-w-[17ch] truncate"
      {...props}
      asChild={false}
    >
      {children}
    </Text>
  );
}
```

**Comment by kevinmitch14** [comment]
I see! Thanks, this worked as expected.

**Comment by kevinmitch14** [comment]
@vladmoroz, I noticed that when using a component like above (a wrapper around a radix themes component), inside a `Tooltip`, I get the forwardRef() error message.

> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Simply wrapping it in a fragment, gets rid of these errors, but should they appear in the first place?

**Comment by kevinmitch14** [comment]
```jsx
function BreadcrumbText({ children, ...props }: React.ComponentPropsWithoutRef<typeof Text>) {
  return <Text {...props}>{children}</Text>;
}
```

The Tooltip won't actually show here. Errors in console.
```jsx
<Tooltip content={"Hello"}>
    <BreadcrumbText>Hello</BreadcrumbText>
</Tooltip>
```


By doing the following, it works again.
```jsx
<Tooltip content={"Hello"}>
  <div>
    <BreadcrumbText>Hello</BreadcrumbText>
  </div>
</Tooltip>
```

**Comment by vladmoroz** [comment]
Right, so you need to forward the ref in your Breadcrumbs component:
https://react.dev/reference/react/forwardRef

In general this is something you'd have to do for all custom components to make sure that interactivity works correctly when they are composed with something else (like the Tooltip in your example).

**Comment by kevinmitch14** [comment]
Hmm I see, I have some other similar components that don't have any issues. If I use the custom component above, outside of a tooltip I don't have issues. It's only when I use it inside the tooltip

**Comment by benoitgrelard** [comment]
Yes, that's normal. That's because `Tooltip` (and others) need to add behaviour to make it functional, typically a ref is needed when the element needs to be measured/located for positioning purposes for example.

**Comment by kevinmitch14** [comment]
Apologies, my bad, I slightly misread the response from Vlad. It makes total sense that interactive components would need this, it just felt a bit wrong putting it on the `Text` component.

In the case where I just wrap it in a `div` and the error messages are no longer shown, is the issue actually solved?

So for example without a forwardRef on `BreadcrumbText`:
```jsx
<Tooltip content={"Hello"}>
  <div>
    <BreadcrumbText>Hello</BreadcrumbText>
  </div>
</Tooltip>
```

The ref would get passed to the `div` correctly without any `forwardRef()`?

**Comment by benoitgrelard** [comment]
It is in the sense that native DOM elements can receive `ref` so it will "work". However, for tooltip to be accessible, the trigger should be an interactive element that's focusable, such as a button or a link.
