### ISSUE TITLE
[Select] asChild prop

### ISSUE THREAD

**Issue by Kearnol** [radix-ui/themes#396]
Select (theme) does not actually accept the asChild prop.... so the trigger cannot easily be manipulated. 

<img width="799" alt="image" src="https://github.com/radix-ui/themes/assets/87956114/c72cb1a0-e012-4564-95bb-d9f07d9d3cd6">

**Comment by vladmoroz** [comment]
We'll remove it from the docs to make it accurate, but why do you need it? How did you expect it to work?

**Comment by jonas-at-uneti** [comment]
I am facing the same issue. In my case, I would like to add an icon before the value. Ideally, I would do this with a slot like on a text field, but as this is not possible (afaik), I want to render a custom button component that has the icon.

**Comment by vladmoroz** [comment]
The upcoming 3.0 version supports Select Trigger children so you will be able to render icons inside the trigger. There's a release candidate available that you can already use ([3.0.0-rc.18-patch.2](https://www.npmjs.com/package/@radix-ui/themes/v/3.0.0-rc.18-patch.2) as of now), but be aware of the [changelog](https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/changelog.md) when upgrading—there’s quite a few breaking changes. 

`asChild` with components that have a both styles and interactivity are a bit problematic/unpredictable so it’s unlikely we'll add that. You can always create a custom select using the base select primitive though.

> I am facing the same issue. In my case, I would like to add an icon before the value.  

Curious what does your design look like?

**Comment by MiracleHorizon** [comment]
@vladmoroz I also had this problem with asChild a couple of days ago. I wanted to use Select component to implement my idea, but because I couldn't use my own trigger component I had to use DropdownMenu.

![Screenshot_30](https://github.com/radix-ui/themes/assets/90560240/5162a5e8-b3c7-4e5b-96d7-1a2786f2de6d)

**Comment by vladmoroz** [comment]
> @vladmoroz I also had this problem with asChild a couple of days ago. I wanted to use Select component to implement my idea, but because I couldn't use my own trigger component I had to use DropdownMenu with radio items.

Did you want an icon button trigger?

**Comment by MiracleHorizon** [comment]
> > @vladmoroz I also had this problem with asChild a couple of days ago. I wanted to use Select component to implement my idea, but because I couldn't use my own trigger component I had to use DropdownMenu with radio items.
> 
> Did you want an icon button trigger?

Yeah, that's pretty much the only thing. Maybe I don't know some features of the library and this is the way to do it?

**Comment by vladmoroz** [comment]
> Yeah, that's pretty much the only thing. Maybe I don't know some features of the library and this is the way to do it?

Yeah using the dropdown menu is how I'd do it too; the main difference between that and the select would be how its value wouldn't be submitted in forms, but that doesn't seem to be the problem here.

**Comment by Kearnol** [comment]
> We'll remove it from the docs to make it accurate, but why do you need it? How did you expect it to work?

Thanks for the follow up!

I too was hoping to add an icon to the select trigger:
<img width="402" alt="image" src="https://github.com/radix-ui/themes/assets/87956114/9e9d4db5-cf28-4933-8586-a734ddd771fd">

My designer handed off a Figma design that included an iconStart prop. The Radix component used in the design linked to some sort of Radix Figma documentation for the Select Tigger (theme) component. See here: 
https://www.figma.com/file/JIVl356ACNyYVsmKgKvDHE/Radix?node-id=1157%3A42010&mode=dev
(image below for those who may not be able to access)

However, I could not find an iconStart prop anywhere in the Select Theme docs... 

So, I wasn't sure if the Figma documentation was something officially provided by Radix, and if it was, why it included props that don't seem to exist.

B) I considered using the Primitive Select Trigger as you suggest, but then I lost all of the base styling that comes with Select Theme, which was unfortunate. It also meant needing to import the primitive select package.

So, then I tried using asChild to create my own custom trigger on Select Theme Trigger... and that's when I posted this issue.

Can you clarify on the Figma piece - is that something provided / supported by Radix, and if so, what is the iconStart prop?  

(Image to Figma docs for Select Trigger [theme]) 
<img width="570" alt="image" src="https://github.com/radix-ui/themes/assets/87956114/0d348810-9073-41a2-a085-6b735c86ce86">

**Comment by vladmoroz** [comment]
I see, that Figma file is unofficial and definitely not the source of truth what props are available or even what the components look like.

I'd suggest you refer to my original answer to resolve the issue as that's something possible to do in the upcoming 3.0 version

**Comment by Kearnol** [comment]
Awesome - appreciate that timely follow up. 

Good to know that Figma file isn't something provided by you all. It had me very confused but looked quite official. 

I'll refer to your original reply. 

Thanks again!
