### ISSUE TITLE
Unsupported Server Component type: undefined

### ISSUE THREAD

**Issue by jd-carroll** [radix-ui/themes#399]
I just upgraded from `3.0.0-rc.13-patch.1` to `3.0.0-rc.18-patch.2`. My build was working fine, but then after the upgrade I started receiving:

```
@client-sites/start: Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
@client-sites/start: Error: Unsupported Server Component type: undefined
@client-sites/start:     at em (/develop/client-workbench/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131932)
@client-sites/start:     at /develop/client-workbench/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142926
@client-sites/start:     at Object.toJSON (/develop/client-workbench/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146504)
@client-sites/start:     at stringify (<anonymous>)
@client-sites/start:     at eR (/develop/client-workbench/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134889)
@client-sites/start:     at eP (/develop/client-workbench/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135332)
@client-sites/start:     at AsyncLocalStorage.run (node:async_hooks:346:14)
@client-sites/start:     at Timeout._onTimeout (/develop/client-workbench/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146956)
@client-sites/start:     at listOnTimeout (node:internal/timers:573:17)
@client-sites/start:     at process.processTimers (node:internal/timers:514:7)
```

Additionally, there are six or so similar errors in the console when I build. The page it is attempting to render is a pretty basic `not-found.tsx` with just text components. But I suspect this error would be thrown for any page and that just happens to be the first page to generate the error.

Not sure what is going on, as always I will assume it is something that I am doing. But then I rolled back to `3.0.0-rc.13-patch.1` and it was all working again.

Not really sure where to start on this, but thought I would share.

**Comment by vladmoroz** [comment]
What does your `not-found.tsx` look like?

**Comment by jd-carroll** [comment]
The issue was a bad patch on my part. 

Why is a patch needed... Exports really do not work for cjs and non-`"moduleResolution": "bundler"` projects.

Specifically (as an example):
```typescript
import { radiusPropDef } from '@radix-ui/themes/props';
```
 does not work. There is no `props` at the root. 

That statement is compiled into something equivalent to:
```typescript
const { radiusPropDef } = require('@radix-ui/themes/props');
```

The only way for cjs projects to access the `props` or `helpers` is to do something like:
```typescript
import { radiusPropDef } from '@radix-ui/themes/dist/cjs/props';
```

Which, fine sure whatever, but sucks.

I get the desire for separating props & helpers and keeping them out of semver (not trying to change that). But for projects that do not meet the above conditions, they have the following options:
1) Do not use any of the utilities from `props` or `helpers`
2) Create a patch which exports `props` and `helpers` with all of the `components`. However, if you create a patch that does this, **you must change the `index.js` under both the `dist/cjs` and `dist/esm` directories**.
3) Migrate your `tsconfig.json` to `"moduleResolution": "bundler"`

Hope this helps

**Comment by vladmoroz** [comment]
How are you using props and helpers from Radix Themes? We don't really expect developers to use them yet, curious about your use case.

There’s two ways to do it properly:
a) Use modern ``"moduleResolution"` values, which are: `"Bundler"`, `"Node16"`, or `"NodeNext"`. This is really how new projects should be set up anyway.
b) Import from the exact path they are exported from, which is `@radix-ui/themes/dist/cjs/props/index.js`. We use this themselves [in the docs](https://github.com/radix-ui/website/blob/main/utils/themes/props.ts) because we didn't have the time to upgrade the project to a modern module resolution value. You can also see that re-exporting like that provides convenient access to Radix Themes internals without having to type the whole thing.

**Comment by jd-carroll** [comment]
If you're developing components "in the style of" radix, then it would be foolish not to re-use them

**Comment by vladmoroz** [comment]
Gotcha, OK that's good to know
