### ISSUE TITLE
[Feature Request] Utility enums for layout props

### ISSUE THREAD

**Issue by kylemh** [radix-ui/themes#408]
I'm working on an app that will be used by many people that aren't so experienced with front-end web development. If I can, I want to use layout props and ditch custom styling entirely. In order to get there, I need access to utility props akin to the ones that tailwind exposes related to layout.

In the same way that [tailwind documentation](https://tailwindcss.com/docs/height#basic-usage) adds helpful context to its utility classes via documentation, I think Radix UI has an opportunity to provide a small set of utility values (like `screen`, `full`, `innerDeviceHeight`, `xl` etc.) with JS Docs _and_ with pages on the documentation site to make a more enjoyable developer experience.

As an aside, there's less to type and more theme safety involved with:
```
className="w-full max-w-xl md:max-w-2xl"
```

Than with:
```
width="100%" maxWidth={{ initial: '1280px', md: '1536px'  }}
```

**Comment by vladmoroz** [comment]
We might provide a breakpoint scale at some point, but there won't be any syntactic sugar on top of normal CSS values like 100% or 100vw—this is completely opposite to how we want people to approach styling.

Nothing prevents you from creating a couple variables to abstract whatever values you want to abstract.

**Comment by kylemh** [comment]
I'd just rather use the import plugin for ESLint to ban the Layout components and make my own then. I'll share back out in this thread when I get to that point.
