### ISSUE TITLE
[DropdownMenu] Implementing a Multilevel Dropdown with TextField.Input as Trigger Component

### ISSUE THREAD

**Issue by dwzkit** [radix-ui/themes#41]
I'm attempting to create a dropdown component that not only behaves like a combobox but also supports multilevel dropdown menus. My current approach involves changing the trigger inside the DropDown component from a Button to TextField.Input. However, this is not working as expected, since Input cannot be focused like a Button and only allows for a click-like interaction.

I'd like the dropdown to behave like a typical dropdown, but the trigger component should be an input field, allowing for text entry, and then a click on this input field should open the dropdown with multilevel menu items.

I'm not sure how to proceed in order to make this work. Has anyone encountered a similar issue or can provide a solution to this problem?

```
      <DropdownMenu.Root>
        <DropdownMenu.Trigger>
          <TextField.Root style={{ border: "0px solid red" }}>
            <TextField.Slot
              style={{
                display: "flex",
                flexDirection: "row",
                justifyContent: "flex-end",
                alignItems: "center",
                border: "0px solid red",
              }}
            >
              <MagnifyingGlassIcon height="16" width="16" />
              {/* {!isFocused && inputRef.current?.value === "" && (
                <div className={cssStyle.fakeCursor}></div>
              )} */}
            </TextField.Slot>
            <TextField.Input
              style={{ border: "0px solid blue" }}
              placeholder="Search the docs…"
            />
          </TextField.Root>
        </DropdownMenu.Trigger>
        <DropdownMenu.Content>
          <DropdownMenu.Item shortcut="⌘ E">Edit</DropdownMenu.Item>
          <DropdownMenu.Item shortcut="⌘ D">Duplicate</DropdownMenu.Item>
          <DropdownMenu.Separator />
          <DropdownMenu.Item shortcut="⌘ N">Archive</DropdownMenu.Item>

          <DropdownMenu.Sub>
            <DropdownMenu.SubTrigger>More</DropdownMenu.SubTrigger>
            <DropdownMenu.SubContent>
              <DropdownMenu.Item>Move to project…</DropdownMenu.Item>
              <DropdownMenu.Item>Move to folder…</DropdownMenu.Item>

              <DropdownMenu.Separator />
              <DropdownMenu.Item>Advanced options…</DropdownMenu.Item>
            </DropdownMenu.SubContent>
          </DropdownMenu.Sub>

          <DropdownMenu.Separator />
          <DropdownMenu.Item>Share</DropdownMenu.Item>
          <DropdownMenu.Item>Add to favorites</DropdownMenu.Item>
          <DropdownMenu.Separator />
          <DropdownMenu.Item shortcut="⌘ ⌫" color="red">
            Delete
          </DropdownMenu.Item>
        </DropdownMenu.Content>
      </DropdownMenu.Root>

```
Any assistance or pointers on how to make this implementation work would be greatly appreciated. Thank you!

**Comment by dwzkit** [comment]
To achieve this effect, I tried using floating-ui, a highly customizable floating element UI system, and managed to achieve the effect I was looking for, but the solution was not elegant. Here is the related issue I posted on floating-ui: https://github.com/floating-ui/floating-ui/issues/2500.

**Comment by trebitowski** [comment]
Sounds like you would find [cmdk](https://github.com/pacocoursey/cmdk) very useful. You should be able to style it to fit well with radix themes.

**Comment by dwzkit** [comment]
> Sounds like you would find [cmdk](https://github.com/pacocoursey/cmdk) very useful. You should be able to style it to work with radix themes.

Wow, that's cool! It looks like this might solve my problem. I see there's a section about Nested items, so I'll study it carefully and give it a try! Thank you so much for your suggestion!

**Comment by dwzkit** [comment]
> Sounds like you would find [cmdk](https://github.com/pacocoursey/cmdk) very useful. You should be able to style it to work with radix themes.

I tried it out, and the functionality is very robust, but the interaction method doesn't quite meet my needs. I need users to be able to control the expansion and contraction of submenus through mouse hovering or keyboard arrow keys. As it stands with cmdk, nested submenu items are accessed by pressing enter, and the parent menu is returned to by pressing the back key. There is a lack of visual interaction between parent menus and submenus.Still, I am very thankful for the assistance provided.

**Comment by trebitowski** [comment]
I've got something working that is pretty close to what you described. It opens the dropdown after the user submits/presses enter in the input. By controlling the dropdown's open state manually we're able to get it to behave how you want.

[Demo](https://stackblitz.com/edit/stackblitz-starters-rbgmee?file=pages%2Findex.js)

```TSX
function InputWithDropdown() {
  const [open, setOpen] = React.useState(false);
  return (
    <DropdownMenu.Root open={open} onOpenChange={setOpen}>
      <DropdownMenu.Trigger disabled>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            setOpen(true);
          }}
        >
          <TextField.Root>
            <TextField.Input placeholder="Search the docs…" />
          </TextField.Root>
        </form>
      </DropdownMenu.Trigger>
      <DropdownMenu.Content>
        <DropdownMenu.Item shortcut="⌘ E">Edit</DropdownMenu.Item>
        <DropdownMenu.Item shortcut="⌘ D">Duplicate</DropdownMenu.Item>
        <DropdownMenu.Separator />
        <DropdownMenu.Item shortcut="⌘ N">Archive</DropdownMenu.Item>

        <DropdownMenu.Sub>
          <DropdownMenu.SubTrigger>More</DropdownMenu.SubTrigger>
          <DropdownMenu.SubContent>
            <DropdownMenu.Item>Move to project…</DropdownMenu.Item>
            <DropdownMenu.Item>Move to folder…</DropdownMenu.Item>

            <DropdownMenu.Separator />
            <DropdownMenu.Item>Advanced options…</DropdownMenu.Item>
          </DropdownMenu.SubContent>
        </DropdownMenu.Sub>

        <DropdownMenu.Separator />
        <DropdownMenu.Item>Share</DropdownMenu.Item>
        <DropdownMenu.Item>Add to favorites</DropdownMenu.Item>
        <DropdownMenu.Separator />
        <DropdownMenu.Item shortcut="⌘ ⌫" color="red">
          Delete
        </DropdownMenu.Item>
      </DropdownMenu.Content>
    </DropdownMenu.Root>
  );
}
```

**Comment by dwzkit** [comment]
> 



> I've got something working that is pretty close to what you described. It opens the dropdown after the user submits/presses enter in the input. By controlling the dropdown's open state manually we're able to get it to behave how you want.
> 
> [Demo](https://stackblitz.com/edit/stackblitz-starters-rbgmee?file=pages%2Findex.js)
> 
> ```tsx
> function InputWithDropdown() {
>   const [open, setOpen] = React.useState(false);
>   return (
>     <DropdownMenu.Root open={open} onOpenChange={setOpen}>
>       <DropdownMenu.Trigger disabled>
>         <form
>           onSubmit={(e) => {
>             e.preventDefault();
>             setOpen(true);
>           }}
>         >
>           <TextField.Root>
>             <TextField.Input placeholder="Search the docs…" />
>           </TextField.Root>
>         </form>
>       </DropdownMenu.Trigger>
>       <DropdownMenu.Content>
>         <DropdownMenu.Item shortcut="⌘ E">Edit</DropdownMenu.Item>
>         <DropdownMenu.Item shortcut="⌘ D">Duplicate</DropdownMenu.Item>
>         <DropdownMenu.Separator />
>         <DropdownMenu.Item shortcut="⌘ N">Archive</DropdownMenu.Item>
> 
>         <DropdownMenu.Sub>
>           <DropdownMenu.SubTrigger>More</DropdownMenu.SubTrigger>
>           <DropdownMenu.SubContent>
>             <DropdownMenu.Item>Move to project…</DropdownMenu.Item>
>             <DropdownMenu.Item>Move to folder…</DropdownMenu.Item>
> 
>             <DropdownMenu.Separator />
>             <DropdownMenu.Item>Advanced options…</DropdownMenu.Item>
>           </DropdownMenu.SubContent>
>         </DropdownMenu.Sub>
> 
>         <DropdownMenu.Separator />
>         <DropdownMenu.Item>Share</DropdownMenu.Item>
>         <DropdownMenu.Item>Add to favorites</DropdownMenu.Item>
>         <DropdownMenu.Separator />
>         <DropdownMenu.Item shortcut="⌘ ⌫" color="red">
>           Delete
>         </DropdownMenu.Item>
>       </DropdownMenu.Content>
>     </DropdownMenu.Root>
>   );
> }
> ```

Thank you very much for your answer, it's indeed very close to my requirements. My goal is to always keep the dropdown expanded when the input content is empty. This includes cases where the input is focused and the dropdown loses focus; the dropdown should still remain open. It will only hide when the input content is not empty, and when the input becomes empty again, the dropdown will re-expand. I tried to listen to the input value and made adjustments to `setOpen` based on whether it was empty or not. Perhaps due to the constraint of the DropdownMenu, where both `open` and `onOpenChange` must be set, the dropdown will default to automatically executing `setOpen` in `onOpenChange` when it loses focus. Therefore, executing `setOpen` under the input value listening condition is ineffective.

```
import {
  Button,
  Dialog,
  DropdownMenu,
  Flex,
  TextField,
} from '@radix-ui/themes';
import Head from 'next/head';
import React from 'react';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Radix Themes Demo</title>
      </Head>

      <main>
        <Flex
          align="center"
          justify="center"
          gap="6"
          style={{ height: '100vh' }}
        >
          <InputWithDropdown />
        </Flex>
      </main>
    </div>
  );
}

function InputWithDropdown() {
  const [open, setOpen] = React.useState(true);
  const [inputValue, setInputValue] = React.useState('');

  const handleInputChange = (e) => {
    const value = e.target.value;
    setInputValue(value);
    setOpen(value === '');
  };
  return (
    <DropdownMenu.Root open={open} onOpenChange={setOpen}>
      <DropdownMenu.Trigger disabled>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            setOpen(true);
          }}
        >
          <TextField.Root>
            <TextField.Input
              placeholder="Search the docs…"
              value={inputValue}
              onChange={handleInputChange}
            />
          </TextField.Root>
        </form>
      </DropdownMenu.Trigger>
      <DropdownMenu.Content>
        <DropdownMenu.Item shortcut="⌘ E">Edit</DropdownMenu.Item>
        <DropdownMenu.Item shortcut="⌘ D">Duplicate</DropdownMenu.Item>
        <DropdownMenu.Separator />
        <DropdownMenu.Item shortcut="⌘ N">Archive</DropdownMenu.Item>

        <DropdownMenu.Sub>
          <DropdownMenu.SubTrigger>More</DropdownMenu.SubTrigger>
          <DropdownMenu.SubContent>
            <DropdownMenu.Item>Move to project…</DropdownMenu.Item>
            <DropdownMenu.Item>Move to folder…</DropdownMenu.Item>

            <DropdownMenu.Separator />
            <DropdownMenu.Item>Advanced options…</DropdownMenu.Item>
          </DropdownMenu.SubContent>
        </DropdownMenu.Sub>

        <DropdownMenu.Separator />
        <DropdownMenu.Item>Share</DropdownMenu.Item>
        <DropdownMenu.Item>Add to favorites</DropdownMenu.Item>
        <DropdownMenu.Separator />
        <DropdownMenu.Item shortcut="⌘ ⌫" color="red">
          Delete
        </DropdownMenu.Item>
      </DropdownMenu.Content>
    </DropdownMenu.Root>
  );
}
```

**Comment by trebitowski** [comment]
There is no need for onOpenChange if the dropdown state is derived purely from the value of the input. Setting modal to false will allow interaction with outside elements while the dropdown is open.

```TSX
function InputWithDropdown() {
  const [value, setValue] = React.useState('');
  return (
    <DropdownMenu.Root open={!value} modal={false}>
      <DropdownMenu.Trigger disabled>
        <TextField.Root>
          <TextField.Input
            value={value}
            onChange={(e) => setValue(e.target.value)}
            placeholder="Search the docs…"
          />
        </TextField.Root>
      </DropdownMenu.Trigger>
      ...
    </DropdownMenu.Root>
  );
}
```

**Comment by dwzkit** [comment]
> There is no need for onOpenChange if the dropdown state is derived purely from the value of the input. Setting the dropdown's modal prop to false will allow interaction with outside elements while the dropdown is open.
> 
> ```tsx
> function InputWithDropdown() {
>   const [value, setValue] = React.useState('');
>   return (
>     <DropdownMenu.Root open={!value} modal={false}>
>       <DropdownMenu.Trigger disabled>
>         <TextField.Root>
>           <TextField.Input
>             value={value}
>             onChange={(e) => setValue(e.target.value)}
>             placeholder="Search the docs…"
>           />
>         </TextField.Root>
>       </DropdownMenu.Trigger>
>       ...
>     </DropdownMenu.Root>
>   );
> }
> ```

Thank you for providing the code! What I am working on now is the development of an interaction feature similar to Notion Ai. In my view, Notion Ai is a combination of an Input and DropDown multi-level menu. Its characteristic is that the focus always remains on the Input box, and through cursor hovering or the use of keyboard arrows, you can conveniently operate the DropDown menu items, including selecting a menu, opening a submenu, hiding a submenu, etc. However, when you need to input content, you don't need to restore the input focus with the mouse first; you can directly input, and the DropDown menu will automatically disappear when inputting content in the input box. Initially, I didn't use any DropDown components but developed a set myself. However, I only implemented a single-level menu effect. When I needed to create embedded, deeper-level menus, I realized that this was a very complex and specialized development task, so I started looking for more suitable solutions.

<img width="914" alt="image" src="https://github.com/floating-ui/floating-ui/assets/41875799/522b5017-c963-46d3-9b1f-152ee3aa3f7e">

**Comment by vladmoroz** [comment]
This might be a cool interaction, but this kind of component complexity isn't something we plan to support with Radix Themes yet—at least not until we build the right primitives for this (like the combobox). Your best bet is to find a headless primitive that works like you need it to work and create custom styles using the Radix Themes tokens.
