### ISSUE TITLE
[RadioGroup] Issue

### ISSUE THREAD

**Issue by techpepson** [radix-ui/themes#417]
I get an error when I pass a child to RadioGroup.Item. The error specifies that RadioGroup.Item takes no children but that is not what is specified in the docs.

**Comment by vladmoroz** [comment]
Are you using the latest version? If yes, what is your code like?

**Comment by vladmoroz** [comment]
I'll close this assuming that you are using an outdated version. In 3.0 RadioGroup.Item accepts children
