### ISSUE TITLE
[TextField] Issue

### ISSUE THREAD

**Issue by IsNott** [radix-ui/themes#422]
In use element TextFied.Root's Property call placeholder show compile error message: Property 'placeholder' does not exist on type 'IntrinsicAttributes & Omit<TextFieldRootProps, "ref"> & RefAttributes<HTMLDivElement>'.ts(2322)

![Snipaste_2024-03-31_12-04-54](https://github.com/radix-ui/themes/assets/96410210/36fd629e-4a24-445b-a54d-21ec1cd2f3a5)

dependencies:{
 ...
"@radix-ui/react-aspect-ratio": "^1.0.3",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/themes": "^2.0.3",
}

**Comment by vladmoroz** [comment]
In 2.0.3 there's a separate `TextField.Input` part to render an input element with its related props.

The docs document the latest 3.0.1 which I'd recommend to upgrade to ideally.
