### ISSUE TITLE
Icons don't receive an underline when in a Link

### ISSUE THREAD

**Issue by Teddarific** [radix-ui/themes#427]
Not sure if this is expected behavior, but icons when wrapped inside a `Link` don't get an underline when hovered.

Here's an example sandbox where you can see it visually + see the source: https://www.magicpatterns.com/ai/editor/cp8m7i4YV9ZmsPkzAxGj7f

As you can see, the icon doesn't receive the underline but the text does.

Here's the code snippet from the above example:
```
function LinkWithIcon() {
  return (
    <Link
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
      }}
    >
      <IconJarLogoIcon />
      Click Here
    </Link>
  );
}
```

**Comment by vladmoroz** [comment]
Yeah, this is by design. Have you seen underline below icons that would look good?

**Comment by Teddarific** [comment]
@vladmoroz Gotcha! Yeah, I was using this site as inspiration: https://deadsimplesites.com/, and really liked their "Visit ->" link where the underline also goes under the arrow. I also think it helps make the underline hover state more visible, but totally get that it goes either way.

**Comment by Teddarific** [comment]
@vladmoroz Ah fascinating, TIL! Thanks for the help. Will use the text character.
