### ISSUE TITLE
Support hover style for Link without href attribute

### ISSUE THREAD

**Issue by LavransBjerkestrand** [radix-ui/themes#428]
Before v3 the Link component didn't require the href attribute to be show the hover style and underline. I found this convenient as I often use it as an inline button of sorts.

This is related to the `any-link` pseudo selector.

Workaround:
```tsx
<Link href="" onClick={(e) => [e.preventDefault(), ...]}>
    ...
</Link>
```

**Comment by vladmoroz** [comment]
Released 3.0.2 with a fix that makes it so that links rendered as buttons retain hover styles.

To clarify, what you seem to be doing is not accessible. You should use the `asChild` prop to render link with `button` tags:

```jsx
<Link asChild>
  <button onClick={...}>Button that looks like link</button>
</Link>
