### ISSUE TITLE
.rt-reset causes trouble for TextArea components

### ISSUE THREAD

**Issue by yemi** [radix-ui/themes#429]
Seems like using `unset: all` disables both regular spaces and line-breaks on `<TextArea />`s.

**Comment by vladmoroz** [comment]
Released 3.0.2 with the fix

**Comment by yemi** [comment]
Thanks! Fyi: seemed to happen in chromium and chrome as well

**Comment by vladmoroz** [comment]
Not seeing it in Chrome and Safari myself, what version and OS do you have?

**Comment by yemi** [comment]
Tried chrome macOS Sonoma 14.4.1 and Chromium in Arch Linux

**Comment by yemi** [comment]
My main is Firefox though and tried it there first

**Comment by yemi** [comment]
Chrome in Mac: 123.0.6312.105
