### ISSUE TITLE
Card renders blank inside a grid while scrolling

### ISSUE THREAD

**Issue by Means88** [radix-ui/themes#442]
Hello, I encountered a problem that cards inside a grid container (native or radix grid) renders blank when scrolling the page.

Browser: Chrome 123.0.6312.107 (arm64) 
OS: macOS 14.4.1
@radix-ui/themes: 3.0.2

Can't be reproduced by macOS Safari and iOS/iPadOS Chrome, but the same issue happens in other Chromium based browsers in macOS.

Here is the reproduction: https://codesandbox.io/p/sandbox/wizardly-brown-z83czm?file=%2Fsrc%2FApp.js%3A34%2C10

https://github.com/radix-ui/themes/assets/5810331/cbf3fed6-cf8d-415c-a56c-e7d2a96d234f

<img width="1301" alt="image" src="https://github.com/radix-ui/themes/assets/5810331/936f7a85-be8e-40ab-9695-bc77204426aa">

**Comment by vladmoroz** [comment]
Card uses a blur background filter which can lead to these issues in certain edge cases.

In your case specifically, just don't nest Card in Card, that seems unnecessary. Browsers don't handle nested background filters well. 

Alternatively, you can set `panelBackground="solid"` on the Theme ([docs](https://www.radix-ui.com/themes/docs/theme/color#panel-background)) to remove the background effect.
