### ISSUE TITLE
How to apply custom `color` names in 3.x?

### ISSUE THREAD

**Issue by mstade** [radix-ui/themes#444]
First of all, big congrats on the 3.0 release of themes – it's really great!

We're in the process of migrating from 2.0, and it's mostly been easy and straight forward thanks to the great change log that seems to cover most breaking changes. There is one however I could find no mention of: it doesn't seem possible to override `color` with custom names anymore.

We've defined semantic color scales like `info`, `error`, `danger` and so on, and would use them with the color prop, like so:
```jsx
<Callout.Root color="danger">
  ...
</Callout.Root>
```

Before the 3.0 release this would yield `data-accent-color="danger"` on the DOM node as expected, however with 3.0 this seems to just yield `data-accent-color`, without value:

<img width="701" alt="Screenshot 2024-04-06 at 22 12 56" src="https://github.com/radix-ui/themes/assets/605731/490d5d20-e9c3-4056-b086-1fa920b311b2">

Doing a cursory review of the code, it looks like it may be this bit that causes the issue:

https://github.com/radix-ui/themes/blob/c7f02af3fc400dadb293a85ba89e437c2dbba54f/packages/radix-ui-themes/src/helpers/extract-props.ts#L43-L50

It looks like #273 introduced this code, but it doesn't seem to be mentioned.

Is there some other way to (ab)use `color` to implement custom color names?

**Comment by vladmoroz** [comment]
Custom color names were never officially supported; that it worked in the first place was a bug.

Just use literal values like `color="red"`

There are no plans to support semantic colors in the component API.

**Comment by mstade** [comment]
Unfortunately this means it's no longer possible to use custom color scaled with Radix Themes anymore, unless you alias one of the existing color names which may or may not fit in any meaningful way.

To benefit anyone else who may run into this, we elected to create enum-like objects to alias the existing scales under custom names, e.g.:

```js
const SemanticColors = /** @type {const} */ ({
  INFO: "sky",
  ERROR: "red",
  DANGER: "red",
  SUCCESS: "green",
  WARNING: "orange,
})
```

For actual custom color scales like brand colors, we'll have to alias one of the existing names to set our custom color values. It's an unfortunate change I think, especially with the introduction of the [custom palette generator](https://www.radix-ui.com/colors/custom), but at least there's a workaround.
