### ISSUE TITLE
Template "radix:views-view" is not defined in "themes/custom/ww_radix_6/templates/views-view.html.twig" 

### ISSUE THREAD

**Issue by toto93700** [radix-ui/themes#445]
Hello all is in my title i stated a fresh drupal install and make install like the docs says but i always got this error and i dont know why my  drupal dont detect this files ..

here the error  :
 The website encountered an unexpected error. Try again later.

Twig\Error\LoaderError: Template "radix:views-view" is not defined in "themes/custom/ww_radix_6/templates/views-view.html.twig" at line 33. in Twig\Loader\ChainLoader->getCacheKey() (line 99 of C:\wamp64\www\my_site_name_dir\vendor\twig\twig\src\Loader\ChainLoader.php).
Twig\Environment->getTemplateClass('radix:views-view', NULL) (Line: 204)
Drupal\Core\Template\TwigEnvironment->getTemplateClass('radix:views-view') (Line: 319)
Twig\Template->loadTemplate('radix:views-view', 'themes/custom/ww_radix_6/templates/views-view.html.twig', 33) (Line: 39)
__TwigTemplate_92e364ab8e6d34a89537c7e638157b9a->doDisplay(Array, Array) (Line: 394)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 367)
Twig\Template->display(Array) (Line: 379)
Twig\Template->render(Array) (Line: 38)
Twig\TemplateWrapper->render(Array) (Line: 39)
twig_render_template('themes/custom/ww_radix_6/templates/views-view.html.twig', Array) (Line: 348)

my content file : 

{#
/**
 * @file
 * Theme override for a main view template.
 *
 * Available variables:
 * - attributes: Remaining HTML attributes for the element.
 * - css_name: A CSS-safe version of the view name.
 * - css_class: The user-specified classes names, if any.
 * - header: The optional header.
 * - footer: The optional footer.
 * - rows: The results of the view query, if any.
 * - empty: The content to display if there are no rows.
 * - pager: The optional pager next/prev links to display.
 * - exposed: Exposed widget form/info to display.
 * - feed_icons: Optional feed icons to display.
 * - more: An optional link to the next page of results.
 * - title: Title of the view, only used when displaying in the admin preview.
 * - title_prefix: Additional output populated by modules, intended to be
 *   displayed in front of the view title.
 * - title_suffix: Additional output populated by modules, intended to be
 *   displayed after the view title.
 * - attachment_before: An optional attachment view to be displayed before the
 *   view content.
 * - attachment_after: An optional attachment view to be displayed after the
 *   view content.
 * - dom_id: Unique id for every view being printed to give unique class for
 *   JavaScript.
 *
 * @see template_preprocess_views_view()
 */
#}
{% include "radix:views-view" %}

**Comment by vladmoroz** [comment]
This project has nothing to do with Drupal, not sure you are in the right place
