### ISSUE TITLE
[Spinner] Issue

### ISSUE THREAD

**Issue by Dns2690** [radix-ui/themes#448]
don't  import from themes

**Comment by vladmoroz** [comment]
I'm not sure I understand—what are you trying to say? What's the issue?

**Comment by Dns2690** [comment]
Hello, sorry, I tried to use the spinner in nextjs14, but it does not
recognize the import from radix-themes , it throws an error, it also did
not auto-import like the other elements do.

**Comment by vladmoroz** [comment]
Are you on the latest version? Spinner was added in 3.0
