### ISSUE TITLE
[theme] - on large screen, theme completely fails to render.

### ISSUE THREAD

**Issue by zemunkh** [radix-ui/themes#449]
Please look at the following image. Our website, that uses some components from Radix-ui also failed to render on big scaled screen.

![IMG_6900](https://github.com/radix-ui/themes/assets/19935251/6664924a-618c-44b0-bdbe-86687a7173aa)

On production, we fail to show it to others.

**Comment by vladmoroz** [comment]
What device and browser version is that?

**Comment by zemunkh** [comment]
Chrome, Windows 10 Touch Screen and its screen size width is more than
3300. You can consider this screen as 4k display

**Comment by vladmoroz** [comment]
The screen size doesn't matter
What's the device and Chrome version exactly?

**Comment by zemunkh** [comment]
It was Browser version. We updated the browser to version 123. Now, it works just fine.

Thank you for your support.
