### ISSUE TITLE
Safari MacOS: thin borders are blurry and inconsistent

### ISSUE THREAD

**Issue by SebKranz** [radix-ui/themes#452]
In Safari (my Version is 17.4.1) borders are blurred:

<img width="529" alt="Screenshot 2024-04-12 at 07 49 49" src="https://github.com/radix-ui/themes/assets/33868262/5f26e5be-f033-4dcd-969a-39254159ea25">

This is well visible both on a 4k screen and the high-resolution internal MacBook display. I wasn't able to test this on a 1x monitor. This issue occurs only on MacOS. iOS looks fine.

If I replace the `box-shadow`s with `border: 1px solid ...` the effect disappears:
<img width="543" alt="Screenshot 2024-04-12 at 07 49 20" src="https://github.com/radix-ui/themes/assets/33868262/230e7495-0572-4bc5-8aa8-b81cafd8e7c9">

**Comment by vladmoroz** [comment]
Looks like you are zoomed in and Safari doesn't seem to handle gracefully compared to other browsers. I don't think we'll reevaluate our use of box-shadows across components because of that. It looks fine at 100% zoom.
