### ISSUE TITLE
[Select] Issue: Ref on Select.Root is not being forwarded

### ISSUE THREAD

**Issue by m-spyratos** [radix-ui/themes#456]
When passing `ref` to [<Select.Root>](https://www.radix-ui.com/themes/docs/components/select) I get the following warning:

> Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Example:

```
import { useRef } from "react";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { Select } from "@radix-ui/themes";

export default function App() {
  const ref = useRef(null);

  return (
    <Theme>
      <Select.Root defaultValue="apple" ref={ref}>
        <Select.Trigger />
        <Select.Content>
          <Select.Item value="orange">Orange</Select.Item>
          <Select.Item value="apple">Apple</Select.Item>
          <Select.Item value="grape" disabled>
            Grape
          </Select.Item>
        </Select.Content>
      </Select.Root>
    </Theme>
  );
}
```

[View on Code Sandbox](https://codesandbox.io/p/sandbox/react-new?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluzunzl10006356kinfj66q2%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluzunzl10002356kth7kdwue%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluzunzl10003356kdi15dw39%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluzunzl10005356kjk0mpf7j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluzunzl10002356kth7kdwue%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluzunzl00001356knxd9b511%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522cluzunzl10002356kth7kdwue%2522%252C%2522activeTabId%2522%253A%2522cluzunzl00001356knxd9b511%2522%257D%252C%2522cluzunzl10005356kjk0mpf7j%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluzunzl10004356kpy6cywi3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cluzunzl10005356kjk0mpf7j%2522%252C%2522activeTabId%2522%253A%2522cluzunzl10004356kpy6cywi3%2522%257D%252C%2522cluzunzl10003356kdi15dw39%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cluzunzl10003356kdi15dw39%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

Version: `3.0.2`

**Comment by vladmoroz** [comment]
Select.Root doesn't render a HTML node, so there's nowhere to forward the ref to
