### ISSUE TITLE
Pseudo Element Variable Access

### ISSUE THREAD

**Issue by jd-carroll** [radix-ui/themes#458]
I am attempting to style a particular portion of my layout with the `::before` pseudo element (an indicator in the side-nav). 

It would [appear as though](https://stackoverflow.com/a/75568833) pseudo elements do not inherit variables defined in a parent (including `:root`).

Has anyone else encountered this? If so, is there an easy way people have found to copy (since that is the only option) all the variable declarations to the pseudo element?

**Comment by vladmoroz** [comment]
> It would appear as though pseudo elements do not inherit variables defined in a parent (including :root).

That's not true, CSS variables are inherited by pseudos just fine.
