### ISSUE TITLE
[Select] Max height of select dropdown

### ISSUE THREAD

**Issue by pnilssson** [radix-ui/themes#460]
Hi!

First of all, thanks for the amazing library. 

I can't manage to set the max height of the select dropdown, is this possible? I cannot make the select input span the entire width either.

All good!

**Comment by vladmoroz** [comment]
> I can't manage to set the max height of the select dropdown, is this possible?

Yep it is, use `position="popper"` and override max height via an inline style on Select.Content part
```
<Select.Content position="popper" style={{ maxHeight: 100 }}>
```

> I cannot make the select input span the entire width either.

Either set `style={{ width: '100%' }}` on the Select.Trigger part, or wrap it in a `<Flex direction="column">` element
