### ISSUE TITLE
[Layout] Extract layout to separated package

### ISSUE THREAD

**Issue by michaltaberski** [radix-ui/themes#466]
Layout components are very handy and can serve a nice building blocks for DesignSystems without styling. Did you consider to move the Layout set of utils to a separated package? Perhaps to package under primitives?

**Comment by kevinmitch14** [comment]
https://www.radix-ui.com/themes/docs/overview/layout#standalone-usage

**Comment by michaltaberski** [comment]
Yes, I have seen this. However installing the whole framework in order to use few utils from it it's quite an overhead, isn't it?

**Comment by vladmoroz** [comment]
We don't plan to extract layout into a separate package. It's integrated tightly into the rest of the library so it would be a significant lift to do that and maintain the two together, which we don't have the resources for.

What bothers you about the suggested approach? There's no "overhead" if your dev tooling can tree-shake the unused parts of the library, which is what most bundlers do today out of the box.

**Comment by michaltaberski** [comment]
Yes, I have checked the source code and I have noticed it's quite a bit of work to extract layout from the repo.

Regarding what's bothering with using the entire radix-ui is not the bundle side grow, but rather additional set of dependencies added only due to the layout utils. 

Anyway, thanks for an explenation 👍

**Comment by vladmoroz** [comment]
If you are building a design system and want to include the layout components, Radix Themes dependencies won't affect anything if you set up the build process to tree-shake the unused components.
