### ISSUE TITLE
Button's ghost variant has inconsistent padding

### ISSUE THREAD

**Issue by aryankarim** [radix-ui/themes#467]
## Bug report

Button's ghost variant has inconsistent padding compared to other buttons. It makes the button have a smaller background when you hover on it.

### Current Behavior

Size of button is smaller when hovering.

![Screenshot 2024-04-20 151411](https://github.com/radix-ui/primitives/assets/58115075/e4fa266c-0963-4319-abcc-a06abb57daff)

### Expected behavior

It should have the same width and height as the other button when hovering.

### Reproducible example

The issue is persistent on the playground.

https://www.radix-ui.com/themes/playground

### Suggested solution

paddings should be consistent with the other buttons.

### Additional context

Not needed.

### Your environment

Not needed.

**Comment by vladmoroz** [comment]
Do you have a reference design where this looks weird, or is it just something you noticed?

This is mostly by design because these are optimised to work well with one another and among links (e.g. in a site header).

Otherwise with reasonable spacing between ghost buttons, the backgrounds would overlap each other on hover, which feels weird.

**Comment by aryankarim** [comment]
Sure! Here is a GIF.

![2024-04-20-18-45-29_HKK7GbMN-ezgif com-video-to-gif-converter](https://github.com/radix-ui/themes/assets/58115075/7678fc10-947d-40c5-ba37-9e5531419c4b)


These are buttons with `variant="outline"`  when I change it to `ghost`, the whole layout is affected. While the parent div has these innocent tailwind classes "flex justify-center gap-2 p-1"

```javascript
<Button variant={isDark ? "outline" : "ghost"}>
   <NavLink href={item.path as string}>{item.name}</NavLink>
</Button>
```

I could just solve the issue with `className={isDark ? "" : "px-4 py-2"}`,  but IMO this is better addressed on the framework.

**Comment by vladmoroz** [comment]
I think you are just missing `align-items: center` on the parent. Ghost buttons mostly behave like plain text in layout, which is what you are seeing; changing variants between light and dark mode is unusual and not something we optimise for.

Your request does make sense in many situations, which we’ll keep tracking under https://github.com/radix-ui/themes/issues/434
