### ISSUE TITLE
TextField autofocus

### ISSUE THREAD

**Issue by jasonsturges** [radix-ui/themes#468]
Could `autofocus` attribute be added to `TextField`?

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus
> The autofocus [global attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) is a Boolean attribute indicating that an element should be focused on page load, or when the [`<dialog>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) that it is part of is displayed.

As in:

```ts
<TextField.Root
  placeholder="Enter your email"
  type="text"
  name="username"
  autoComplete="username"
  autofocus
  required
/>
```

Currently have to use a ref with callback, like `useCallback(el => el.focus(), [])`

Or, just:

```ts
<TextField.Root
  ref={(el) => el?.focus()}
/>
```

Would be nice for things like search / login forms.

**Comment by vladmoroz** [comment]
It's there, this attribute is just named `autoFocus` in React
