### ISSUE TITLE
Cannot find module `@radix-ui\themes\dist\cjs`

### ISSUE THREAD

**Issue by sapondanaisriwan** [radix-ui/themes#473]
I have no idea why it happened or i miss something?
Repo to reproduce: https://github.com/sapondanaisriwan/reproducible-radix-ui-themes
![24-04-24_21-56](https://github.com/radix-ui/themes/assets/64634605/528107a8-0e6d-42cd-8382-f78826d1431e)

**Comment by vladmoroz** [comment]
You should import from `@radix-ui/themes`, not from `@radix-ui/themes/dist/cjs`

**Comment by sapondanaisriwan** [comment]
Oh Thank you!
