### ISSUE TITLE
[Question] Why separate layout, margin and another props?

### ISSUE THREAD

**Issue by papalardo** [radix-ui/themes#483]
Hi, thanks for the wonderful work.

I have the question about separation some props from definitions, like this:
![image](https://github.com/radix-ui/themes/assets/17734894/2a2f5179-eff5-4c79-ba34-e88d394f50fa)

Why just not merge on componente defs like this?
![image](https://github.com/radix-ui/themes/assets/17734894/d4ef6110-6d5c-4c17-a018-85052bdd9f1e)

I have learned a lot from the source code and the structure they built, but I had this question.

**Comment by vladmoroz** [comment]
This is because prop defs are consumed by the component docs. All component props automatically show up in the prop tables, and we don't want to display the margin props on every component page as they are available almost universally.
