### ISSUE TITLE
[DropdownMenu] Issue- Dropdown can't be navigated with TAB key

### ISSUE THREAD

**Issue by bauerbach** [radix-ui/themes#484]
I tested the dropdown on the documentation page and only the arrow keys can be used to navigate between items. Also, there's nothing about dropdown roles (assuming those exist) in the code.

**Comment by kevinmitch14** [comment]
https://www.radix-ui.com/primitives/docs/components/dropdown-menu#accessibility

**Comment by vladmoroz** [comment]
This is by design, native menus can't be navigated with a Tab key either.
