### ISSUE TITLE
[RadioCards] Issue with import RadioCard

### ISSUE THREAD

**Issue by machuwey** [radix-ui/themes#494]
Hello,
I'm trying to import RadioCard but seems that it is not correctly exported from the radix package or there is some kind of bug.
<img width="810" alt="image" src="https://github.com/radix-ui/themes/assets/56169780/8f689855-1837-4dbc-93ae-c410a38e74f5">

**Comment by vladmoroz** [comment]
Looks like you are on an older version, but Radio Cards were added in 3.0.
