### ISSUE TITLE
[Feature request] Export components prop defs constants

### ISSUE THREAD

**Issue by ch3ric** [radix-ui/themes#498]
**Context**

Example with the `Badge` component:

This component props are defined in https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/components/badge.props.ts#L14 : we can see here for example that we have all possible values of the `variant` prop.

Then these props are used internaly in the Badge component to build the BadgeProps typescript type : https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/components/badge.tsx#L39

And only this typescript type BadgeProps is being exported in the end.

**Request**

It would be great to also export the original `badgePropDefs` that I'd like to be able to use from a Storybook documentation with something like that for example:

```
const meta: Meta<typeof Badge> = {
  title: 'Atoms/Badge',
  component: Badge,
  argTypes: {
    children: Children,
    variant: {
      options: badgePropDefs.variant.values, // here is what I need
      control: { type: 'select' },
    },
  },
};
export default meta;

const Template: StoryFn<typeof Badge> = (args: BadgeProps) => (
  <Badge {...args} />
);
```

If there is another workaround to do what I need, please let me know.

Also I would be happy to contribute to this change if needed.

**Comment by laurentlouk** [comment]
I've had the same issue, is there a reason not to export these?

**Comment by vladmoroz** [comment]
They are already exported from `@radix-ui/themes/props`, see more details here:
https://github.com/radix-ui/themes/issues/333#issuecomment-1976182447
