### ISSUE TITLE
[Card] Issue

### ISSUE THREAD

**Issue by wildrap** [radix-ui/themes#5]
There is no card component on radix-ui themes. The card `<Card>` causes the react app "Cannot find module 'card' on @radix-ui/themes"

**Comment by shfrmn** [comment]
@wildrap I'm not associated with this repo, but just FYI it works fine for me, so it's probably something with your setup (module system, bundler or just need to reinstall/restart without config changes).. I did experience some glitches like this though when trying to import the css file, but after a few restarts it got resolved magically. I'm using the most standard vite+typescrypt setup.

**Comment by vladmoroz** [comment]
@wildrap I can confirm that the card is exported as we are using it on [radix-ui.com](https://radix-ui.com) all over the place. Are you able to import any other component?

Here's what it should look like:
```js
import { Card } from '@radix-ui/themes';
```

**Comment by wildrap** [comment]
Yes I am able to import other component except for the card.

**Comment by vladmoroz** [comment]
Can you put together a minimal example that reproduces this? What is your setup?

**Comment by vladmoroz** [comment]
I'll close this for now as we can’t reproduce this issue and no reproduction is provided
