### ISSUE TITLE
Can't set Select component width to 100%

### ISSUE THREAD

**Issue by greengem** [radix-ui/themes#503]

**Comment by vladmoroz** [comment]
> Can't set Select component width to 100%

What have you tried?

You can set the width via `style={{ width: "100%" }}` on the Trigger, or via layout components, by nesting it in `<Flex direction="column">`

**Comment by greengem** [comment]
> > Can't set Select component width to 100%
> 
> What have you tried?
> 
> You can set the width via `style={{ width: "100%" }}` on the Trigger, or via layout components, by nesting it in `<Flex direction="column">`

Thanks. I've tried styling inline and with css classes on both Select.Trigger and Select.Content to no avail. I'll try to set up a reproduction of the issue asap
