### ISSUE TITLE
border on textfield goes outside the bounds

### ISSUE THREAD

**Issue by jonschmidt** [radix-ui/themes#504]
I am using a textfield from radix themes. When focused, the outline runs partiall outside the bounds
![image](https://github.com/radix-ui/themes/assets/513206/7d60ec97-f29f-4026-a740-83152c5ebdef)

I feel my usage is pretty straightforward. If I change the selector below to make the offset -2px, then it looks perfect. Is this a bug or is something else affecting this?

```
@supports selector(:has(*)) {
    .rt-TextFieldRoot:where(:has(.rt-TextFieldInput:focus)) {
        outline: 2px solid var(--text-field-focus-color);
        outline-offset: -1px
    }
}
```

**Comment by vladmoroz** [comment]
This isn't a bug, that’s by design.

It's pretty typical for focus outlines to go on the outside to make the focused element easier to see. Why is it a problem for you?

**Comment by jonschmidt** [comment]
Its just that its cutoff in my case. I think I must have some overflow setting set incorrectly. I will mess around with it. I am a backend dev masquerading as a front end dev currently!

**Comment by jonschmidt** [comment]
I found it, there was an ancestor with `overflow: auto` set from some time ago. Removing that fixed it. Thanks and sorry for the noise!

**Comment by vladmoroz** [comment]
No worries!
