### ISSUE TITLE
`truncate` property of `<Code>`, doesn't

### ISSUE THREAD

**Issue by steveluscher** [radix-ui/themes#506]
Elements like `<Heading>` and `<Text>` truncate well, but `<Code>` does not, despite supporting the `truncate` property.

<img width="327" alt="image" src="https://github.com/radix-ui/themes/assets/13243/48f7dfb8-9aaf-4289-a0ea-cfa25d6b3782">

[Sandbox link](https://codesandbox.io/p/sandbox/serene-surf-kkfz9w?file=%2Fsrc%2FApp.tsx%3A5%2C10&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwiftwwp00063b6mjr4doqkj%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwiftwwp00023b6mmogov3et%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwiftwwp00033b6muhtsudp9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwiftwwp00053b6m0twvnh5i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwiftwwp00023b6mmogov3et%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwiftwwp00013b6m8djyhnvz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwifucrz00353b6mxp9zxe27%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A10%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwiftwwp00023b6mmogov3et%2522%252C%2522activeTabId%2522%253A%2522clwifucrz00353b6mxp9zxe27%2522%257D%252C%2522clwiftwwp00053b6m0twvnh5i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwiftwwp00043b6m5kovdwkv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwiftwwp00053b6m0twvnh5i%2522%252C%2522activeTabId%2522%253A%2522clwiftwwp00043b6m5kovdwkv%2522%257D%252C%2522clwiftwwp00033b6muhtsudp9%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwiftwwp00033b6muhtsudp9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

**Comment by vladmoroz** [comment]
It's a bit unintuitive, but the truncated element either needs `display: block`, which Heading has naturally and Text has via `as="p"` in your example, or it has to be a child of a flex or grid container.

That’s just the nature of the CSS properties that are added with `truncate`. We can't correct for that ourselves e.g. by adding `display: block` because it can have other unintended consequences to the layout.
