### ISSUE TITLE
[CheckboxGroup] `onValueChange` callback type is `string[]`

### ISSUE THREAD

**Issue by kevinmitch14** [radix-ui/themes#508]
I noticed the onValueChange callback for CheckboxGroup has a type of string[]. Instead of working with the item value that was just checked, the callback receives the array of all checked items.

Is this by design? I feel that other components/primitives provide the freshly chosen value instead of an array of all selected values.

<img width="437" alt="Screenshot 2024-05-23 at 23 11 34" src="https://github.com/radix-ui/themes/assets/55989505/62e0246f-d20c-45bb-8c34-8d9be2953e24">

**Comment by kevinmitch14** [comment]
Looking at https://www.radix-ui.com/primitives/docs/components/toggle-group it follows the same types as above. Will close as I presume this is expected behaviour!

**Comment by vladmoroz** [comment]
Yes, this is by design, it returns an array as you are working with a list of values. The `value` prop is also an array.
