### ISSUE TITLE
TextInput not working neither via dot syntax or neither via explicity importing

### ISSUE THREAD

**Issue by Sameerthe-Big-O** [radix-ui/themes#512]
**Property 'Input' does not exist on type 'typeof import("c:/Users/PMYLS/Desktop/next-js-learning/issue-tracker/node_modules/@radix-ui/themes/dist/esm/components/text-field")'**

```
 <TextField.Root>
          <TextField.Input />
        </TextField.Root>
```
    
**first I tried this approach as well where  it wasn't able to infer Input then I searched and saw there was already issue created and answer to import like**
`
import { TextField ,TextFieldInput} from "@radix-ui/themes"`
but this didn't work for me either at this point don't know what to do

there 
```
"dependencies": {
    "@prisma/client": "^5.14.0",
    "@radix-ui/themes": "^3.0.5",
    "next": "14.2.3",
    "react": "^18",
    "react-dom": "^18",
    "react-hook-form": "^7.51.5",
    "react-icons": "^5.2.1",
    "zod": "^3.23.8"
  },
```

**Comment by vladmoroz** [comment]
How are you importing the component exactly?

**Comment by Sameerthe-Big-O** [comment]
yes exactly what you told in the previous issue

**Comment by vladmoroz** [comment]
Yeah, there was a breaking change at some point with the parts available on the component

**Comment by patrickaigbogun** [comment]
just got an issue with this, what do i do to resolve this
