### ISSUE TITLE
Text component is breaking the app

### ISSUE THREAD

**Issue by pavlelekic** [radix-ui/themes#519]
I created a simple nextjs14 app, installed Radix Themes, created a simple page:
```
export default function Home() {
  return (
    <Flex direction="column" gap="3">
      <Text size="1">The quick brown fox jumps over the lazy dog.</Text>
    </Flex>
  );
}
```
I immediately got an error:
<img width="666" alt="Screenshot 2024-05-31 at 7 09 03 AM" src="https://github.com/radix-ui/themes/assets/7754193/3fba85ca-bc14-4b5f-a2f3-7caa737a232c">

As soon as I remove the `<Text>` component the app renders fine. Has anyone encountered an error like this?

**Comment by vladmoroz** [comment]
This error is not related to the Text component or Radix Themes, sounds like you might be missing a root layout with a `html` and `body` element.
