### ISSUE TITLE
Link as button and vice versa

### ISSUE THREAD

**Issue by milesj** [radix-ui/themes#52]
👋  Enjoying the lib, but one thing I haven't been able to easily figure out is how to treat `Link` as a button, and `Button` as a link. For example, want to do these while preserving the original styles:

```ts
<Button href="...">View</Button>
<Link onClick={doSomething}>View</Link>
```

**Comment by kevinmitch14** [comment]
Use the `asChild` prop to compose Radix's functionality onto alternative element types or your own React components. Radix has a composition guide at https://www.radix-ui.com/primitives/docs/guides/composition 


> All Radix primitive parts that render a DOM element accept an asChild prop. When asChild is set to true, Radix will not render a default DOM element, instead cloning the part's child and passing it the props and behavior required to make it functional.

```js
<Button asChild>
    <a href="...">Click Me!</a>
    // OR: <Link href="...">Click Me!</Link>
</Button>
```

The above code will render an `<a>` element, but will look like a `<Button>`.

**Comment by milesj** [comment]
Awesome, that worked, thanks!
