### ISSUE TITLE
How to specifically manipulate `input` from RT Input without creating pure CSS? >= V3.0.0

### ISSUE THREAD

**Issue by arthurgeron** [radix-ui/themes#521]
Beforehand, we could have specific customization of input field via `Input.Field`, with V3 changes that is no longer possible. Props are moved to `Input.Root` and className only applies to the container.

While we could beautifully stylize and change Input components before:
<img width="410" alt="Screenshot 2024-06-04 at 15 18 04" src="https://github.com/radix-ui/themes/assets/3487334/518a77b5-56a2-4d2b-ab8f-639477c35c6d">

Now it makes that decision for us and forces a horizontal distribution of all children:
<img width="413" alt="Screenshot 2024-06-04 at 15 18 12" src="https://github.com/radix-ui/themes/assets/3487334/6a84418e-1b68-4c56-9a86-06ec4b1fbedb">

It'd make it easier to modify that if I could set style/tailwind class names directly in the `input` element, which is no longer accessible via React Scope.

Our design system also "componentizes" pieces of a Component (e.g. Input.Field, Input.Slot, etc.) pretty much in the same way RT does with as few modifications as possible, so workarounds would break our standard and possibly create accessibility issues. 

I'm also curious as to why to create such an impactful change in how components are utilized, this is such a big breaking change that I'm having a hard time understanding the reason behind it, also are we done with changes like this?

**Comment by vladmoroz** [comment]
We don't prioritise making extensive style overrides easy or backwards-compatible. Heavily overriding styles is bound to be fragile in a pre-styled library, and it will break your design in unexpected ways after upgrades.

Your design looks like a totally custom component to me though.

See the docs on this topic:

https://www.radix-ui.com/themes/docs/overview/styling
