### ISSUE TITLE
Focus styles not applied to `Select.Trigger`

### ISSUE THREAD

**Issue by kevinmitch14** [radix-ui/themes#529]
Recently noticed there are no focus styles for the `Select.Trigger` component. Having a look at the [Select Primitive](https://www.radix-ui.com/primitives/docs/components/select), it seems a focus is added in the CSS. Wondering if this is intentional or not? Happy to open a PR if not intentional.

**Comment by vladmoroz** [comment]
There are focus styles on `Select.Trigger` in Radix Themes. I'm not sure I follow—what is missing exactly? 

<img width="572" alt="image" src="https://github.com/radix-ui/themes/assets/8441036/4e65fbbf-5460-42ae-ba86-6a946685b779">

**Comment by kevinmitch14** [comment]
Fresh navigation vs hard refresh! Weird

https://github.com/radix-ui/themes/assets/55989505/19ee3825-4af7-4891-88e7-4d1f60f1e1fe

**Comment by vladmoroz** [comment]
The difference you see is due to the browser heuristics on when to show `:focus-visible` styles for programmatic focus, not to do with the Select specifically

**Comment by kevinmitch14** [comment]
So if I am navigating around my web app and reach a page with a Select + interact with it, the focus styles will not be shown.

But if perform a hard refresh, or visit the page directly without any soft navigations + interact with it, the focus styles will be shown? 

ie. The component acts differently when someone lands directly on the page versus browsing on the site for some time navigating around?

What is the reasoning behind this? In comparison to the Primitives example uses plain focus. 

Is there a recommended pattern to use Select with a label in this case? Because it doesn't work as you'd expect.

**Comment by vladmoroz** [comment]
> The component acts differently when someone lands directly on the page versus browsing on the site for some time navigating around?

This is a bug in the browser with :focus-visible selector, not something we do intentionally. You can see it with some other components too, like Slider.

The Primitives examples were created when :focus-visible wasn't supported across all browsers so they use just :focus.
