### ISSUE TITLE
Radix UI Theme Button not styled in Remix app when inside Popover

### ISSUE THREAD

**Issue by bkyerv** [radix-ui/themes#532]
Title: Radix UI Theme Button not styled in Remix app when inside Popover

I'm building a Remix app and I'm encountering an issue with Radix UI Theme components, specifically the Button component, when used inside a Popover.

My setup:
- Remix framework
- Radix UI Themes for styling
- @radix-ui/react-popover for the Popover component

Issue:
I have a Button component from Radix UI Themes that opens a Popover. Inside this Popover, I have a form with another Button component for submission. The Button outside the Popover is styled correctly, but the one inside the Popover (for form submission) is not receiving any styles from Radix UI Themes.

Here's a simplified version of my code:

```jsx
import { Button } from "@radix-ui/themes";
import * as Popover from "@radix-ui/react-popover";

export default function UserFeedback() {
  return (
    <Popover.Root>
      <Popover.Trigger asChild>
        <Button variant="solid" size="3">Open Feedback</Button>
      </Popover.Trigger>
      <Popover.Portal>
        <Popover.Content>
          <form>
            <textarea name="userFeedback" />
            <Button variant="soft" size="2">Submit</Button>
          </form>
        </Popover.Content>
      </Popover.Portal>
    </Popover.Root>
  );
}

The "Open Feedback" button is styled correctly, but the "Submit" button inside the Popover is not.
Questions:

Is this a known issue with Radix UI Themes in Remix applications?
Do I need to wrap my Popover content with a Theme provider, and if so, what's the best way to do this in a Remix app?
Are there any specific considerations or best practices for using Radix UI Themes with Remix, especially when components are rendered in portals?

Any insights or suggestions would be greatly appreciated. Thank you!

**Comment by vladmoroz** [comment]
See https://www.radix-ui.com/themes/docs/overview/styling#missing-styles-in-portals

**Comment by bkyerv** [comment]
Спасибо, Володя, попробую сейчас
