### ISSUE TITLE
Added merge cell api for grid layout

### ISSUE THREAD

**Issue by dearming623** [radix-ui/themes#538]
How to peace the cells in it. 
![1719908325751](https://github.com/radix-ui/themes/assets/13852039/4ddb3c1f-133e-4d60-a926-c2fa88bc510c)
Can I merge GHLM cells?

**Comment by chaocwu** [comment]
I am not sure if it is useful to you

![image](https://github.com/radix-ui/themes/assets/143390961/0358d60d-bcb7-4155-9074-9fda3de80158)
![image](https://github.com/radix-ui/themes/assets/143390961/9ad1f1a2-1042-436d-aa17-7ea086438028)
