### ISSUE TITLE
Support Display Vertical Font API

### ISSUE THREAD

**Issue by dearming623** [radix-ui/themes#540]
How to display fonts vertically, use the Text label, and the mouse cursor is displayed normally. Thank you. 

Can we add some apis? Such as
<Text orientation="vertical " textGap="0">radix-ui is so good</Text>

**Comment by vladmoroz** [comment]
What are you looking to achieve exactly? Do you have examples?

**Comment by dearming623** [comment]
> What are you looking to achieve exactly? Do you have examples?
Thank you for your reply.

Like this "<Text orientation="vertical" textGap="0">radix-ui</Text>" 
The result is as follows
 r
a
d
i
x
-
u
i

Also the feature I want to implement is the width of the component according to the width of each word.

**Comment by vladmoroz** [comment]
You can achieve that style with normal CSS. We have no plans do add this as a prop, as it's pretty niche.
