### ISSUE TITLE
[Tooltip] Issue - Tool tip is not rendering 

### ISSUE THREAD

**Issue by karan316** [radix-ui/themes#552]
this is the tool tip component in my design system using radix themes tooltip
```jsx
import React from "react";
import {
	Tooltip as RadixTooltip,
	TooltipProps as RadixTooltipProps,
} from "@radix-ui/themes";

export interface TooltipProps extends RadixTooltipProps {}

const Tooltip: React.FC<TooltipProps> = ({ children, ...props }) => {
	return <RadixTooltip {...props}>{children}</RadixTooltip>;
};

export { Tooltip };

```

I am using it like this 

```jsx
<Tooltip content="Add to library">
  <IconButton radius="full">
    <PlusIcon />
  </IconButton>
</Tooltip>
```

I rendered this inside storybook and used the component in my application as well. The pop up does not show up. Am I missing something here ? i'm using other components from radix and they're working fine. 
I am on React 18.2.0

**Comment by vladmoroz** [comment]
The tooltips definitely work, you might be missing something obvious. Here's one on [workos.com/docs](https://workos.com/docs):

<img width="337" alt="image" src="https://github.com/user-attachments/assets/cfe147b1-a5cc-410a-b529-1cd28448e974">

Can you put together a reproduction?

**Comment by karan316** [comment]
Here is a [codesandbox](https://codesandbox.io/p/sandbox/radix-ui-tooltip-8rydjk?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clz9nlw3z00063b6emadez2ni%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clz9nlw3y00023b6ed51s0ptd%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clz9nlw3y00033b6egehlpmzj%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clz9nlw3y00053b6e88bopys5%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clz9nlw3y00023b6ed51s0ptd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz9nlw3y00013b6exgv8fsu3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clz9ocfxa00023b6e9ynk4xwm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FTooltip.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clz9nlw3y00023b6ed51s0ptd%2522%252C%2522activeTabId%2522%253A%2522clz9ocfxa00023b6e9ynk4xwm%2522%257D%252C%2522clz9nlw3y00053b6e88bopys5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz9nlw3y00043b6es8irb1lc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522clz9nlw3y00053b6e88bopys5%2522%252C%2522activeTabId%2522%253A%2522clz9nlw3y00043b6es8irb1lc%2522%257D%252C%2522clz9nlw3y00033b6egehlpmzj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clz9nlw3y00033b6egehlpmzj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

There problem occurs when I use my design system `IconButton` or `Button` which just wraps around components from radix with some added styles. Am I supposed to pass some additional props to my design system components?

**Comment by kevinmitch14** [comment]
Missing `React.forwardRef` maybe? https://www.radix-ui.com/primitives/docs/guides/composition#composing-with-your-own-react-components

**Comment by vladmoroz** [comment]
You need to forward the refs in your components
https://www.radix-ui.com/primitives/docs/guides/composition#your-component-must-forward-ref
