### ISSUE TITLE
ThemePanel not showing up correctly.

### ISSUE THREAD

**Issue by daskabe** [radix-ui/themes#554]
This is what i see themePanel loads. I dont see the colors etc. Not sure why. 

https://github.com/user-attachments/assets/9b6f3b5f-43af-49d7-8617-5dec08fc7ecb

**Comment by kevinuehara** [comment]
Will can display if is there's some errors on console.log or some log in you application when it's running?

**Comment by vladmoroz** [comment]
That's weird, I can see other components look OK. Can you share a reproduction on CodeSandbox or just link to the repo with the code?

**Comment by daskabe** [comment]
it seems like its tailwind import overriding/adding some styling. but i created a new repo on stackblitz and it doesnt seem to affect it. So i am not sure what the diff is locally. 
https://stackblitz.com/edit/vitejs-vite-awevpb?file=src%2Findex.css

https://github.com/user-attachments/assets/7c6b09c9-afb6-4d2f-a9d4-16f190ad3588

**Comment by kevinuehara** [comment]
Here locally is running normally. What version of node are you using?
I use Node 18 with `yarn`

![image](https://github.com/user-attachments/assets/cb1c4656-be15-418d-aeed-8e18b15686b8)

**Comment by daskabe** [comment]
this is my setup
(base) ➜  node -v
v18.19.0
(base) ➜  npm -v
10.2.3
(base) ➜  tsc -v
Version 5.3.3

**Comment by vladmoroz** [comment]
This seems inline with the Tailwind issues reported now and then. Make sure that TW base styles don't override Radix Themes:
https://www.radix-ui.com/themes/docs/overview/styling#tailwind-base-styles
