### ISSUE TITLE
ScrollArea Axis Locking

### ISSUE THREAD

**Issue by joepetrillo** [radix-ui/themes#560]
I am using ScrollArea on a table to handle x and y overflow. On non-touch based devices, this is working great. However, on mobile or touch screen devices, the scrolling can be a bit annoying. 

If we want to scroll straight down there is a high chance the user will accidentally scroll slightly horizontally.

I think an option to restrict scrolling to one axis at a time (whatever direction started first) would greatly improve the user experience and feel more familiar/expected. See the video below for a simple example. I start by dragging anywhere on the ScrollArea. At the end, I am manually scrolling by manually dragging the scrollbars.

https://github.com/user-attachments/assets/57e7c95f-3675-4695-8182-6b385e72a1dd

**Comment by vladmoroz** [comment]
This isn't planned. Scroll Area component does not hijack the scrolling behaviour in any way. It just styles the scrollbars and uses the browser's native scrolling.
