### ISSUE TITLE
Radix Themes will support Radix Primitives components?

### ISSUE THREAD

**Issue by tjhoo** [radix-ui/themes#58]
Hi

Will Radix Themes support all components from Radix Primitives like [accordion](https://www.radix-ui.com/primitives/docs/components/accordion), [label](https://www.radix-ui.com/primitives/docs/components/label), [form](https://www.radix-ui.com/primitives/docs/components/form) and the rest?

**Comment by needim** [comment]
Eventually, I believe :)

**Comment by tjhoo** [comment]
@needim It would be very helpful if we know the roadmap of when Radix Themes will support the components from Primitives.

**Comment by vladmoroz** [comment]
Yes, we plan on adding more components over time
