### ISSUE TITLE
Error while trying to use radix theme with pre-configured cloudflare pages (next.js) command

### ISSUE THREAD

**Issue by trace2798** [radix-ui/themes#595]
When I tried to use Radix theme with Next.js and Cloudflare pages, during the build process I got this error
```
Failed to compile.

./node_modules/@radix-ui/react-primitive/dist/index.mjs
Attempted import error: 'flushSync' is not exported from 'react-dom' (imported as 'ReactDOM')
```
To reproduce:
1. You can clone this [repo](https://github.com/trace2798/latest-test-cf-nx-radix) and try it yourself. 

Steps I took to create it:
1. Using the following command to create a Next.js app pre-configured with Cloudflare 
```
npm create cloudflare@latest -- my-next-app --framework=next
```
2. Following the get started guide from [radix](https://www.radix-ui.com/themes/docs/overview/getting-started)

![image](https://github.com/user-attachments/assets/7ff24e30-fa9c-4696-9e9b-c97c5a516ea0)

In the past, I have used radix theme in a similar way and it always worked flawlessly.

**Comment by rgabriel01** [comment]
we have the very same issue as well

**Comment by rgabriel01** [comment]
This normally happens when runtime is edge

**Comment by trace2798** [comment]
Yup. I just moved back to shadcn/ui

**Comment by Mista-Shelby** [comment]
Hi,
Exact same issue here :( I built my whole app with radix UI components, everything was working fine locally but now I can't compile.
Anybody has a workaround or should I rewrite all my components ?

**Comment by nkg168** [comment]
Probably because layout.tsx, which imports Theme, is server components.
https://github.com/trace2798/latest-test-cf-nx-radix/blob/master/app/layout.tsx

The following may be helpful.
https://github.com/snelsi/nextjs-radix-themes-template/blob/main/src/app/providers.tsx#L1

**Comment by Mista-Shelby** [comment]
> Probably because layout.tsx, which imports Theme, is server components. https://github.com/trace2798/latest-test-cf-nx-radix/blob/master/app/layout.tsx
> 
> The following may be helpful. https://github.com/snelsi/nextjs-radix-themes-template/blob/main/src/app/providers.tsx#L1

That worked flawlessly, thank you so much !

**Comment by rgabriel01** [comment]
yup the above solutions works!
Just to tinker a bit, is there a way without using 'use client' ?

**Comment by Housi** [comment]
This example is client component, so it's not possible to render RSC with radix themes on the edge?

**Comment by Eigilak** [comment]
👀

**Comment by trace2798** [comment]
@Housi yes, I ran into that problem after closing the issue. So I just moved away from radix-theme for now. For now I am using radix-primitives and shadcn/ui without any issue.
