### ISSUE TITLE
[ThemePanel - Bug] Appearance switch of ThemePanel doesn't work properly

### ISSUE THREAD

**Issue by w1that** [radix-ui/themes#6]
I tried the ThemePanel at [play ground](https://www.radix-ui.com/themes/playground) and wanted to add it to my React application. 

I use `<Theme appearance="dark" accentColor="tomato" grayColor="sage">`, so I set the appearance to `dark` as default. When I start the app, the Light radio input is selected, while the Panel is in dark theme. After clicking on Light radio input, it turns to Light theme but the dark theme radio input can't be selected. 

I guess it is because of class of the `ThemePanel` can't find a way to change from `light` to `dark`

**Comment by shfrmn** [comment]
I also encountered this bug yesterday, but didn't want to open the first issue in the new repo 😅 

@w1that As an ugly temporary solution you can add this to your root component.
```jsx
  useEffect(() => {
    const root = document.getElementById("root")!
    const script = root.querySelector("script")!
    const scriptCopy = document.createElement("script")
    scriptCopy.innerText = script.innerText!
    root.appendChild(scriptCopy!)
  }, [])
```

The bug is caused by the fact `ExplicitRootAppearanceScript` doesn't actually execute or misfires in some way. I wasn't able to immediately understand what happens.
https://github.com/radix-ui/themes/blob/39f5a438db0d8496134d4bc35d71899fee1b2562/packages/radix-ui-themes/src/theme.tsx#L84

**Comment by vladmoroz** [comment]
Thanks for raising the issue, we'll look into it. What is your setup exactly?

If you need just the dark mode, could you try this:
1. If you have access to the `html` element, set `class="dark"` or `class="dark-theme"`
2. Then, just don't pass the `appearance` prop on the `Theme` component

**Comment by shfrmn** [comment]
@vladmoroz Should be very easy to reproduce. Just create a new react app using yarn+vite+typescript, then yarn add the library and wrap everything with `<Theme appearance="dark">`

Regarding adding `class="dark"` no doubt it will start working after that. What I found is that the code inside `ExplicitRootAppearanceScript` works perfectly when executed manually in the console, so I figured it probably just doesn't run when you inject the script tag for whatever reason. In the solution I posted above I just reinsert the script tag as you can see and the theme setup happens as you intended.

**Comment by w1that** [comment]
As @shfrmn said, I just created a new React app with CRA-typescript template. 

I use the `Template` and `TemplatePanel` in index.tsx like this (_as suggested at the docs_):
```
<Theme appearance="dark" accentColor="tomato" grayColor="sage">
    <App />
    <ThemePanel />
  </Theme>
```

Here is a video that shows how it works:

https://github.com/radix-ui/themes/assets/62015683/bd52303d-d73c-4dbe-ad3d-b07a4f615c82

**Comment by jd-carroll** [comment]
I bet this is also related to #22
