### ISSUE TITLE
`asChild` prop not available on `<Table>` components.

### ISSUE THREAD

**Issue by kevinmitch14** [radix-ui/themes#61]
`asChild` prop  doesn't exist when on the `<Table>` components, can't seem to find any reference to asChild in the table.d.ts file. Docs mention that it should be available on multiple table components. 

Using the latest version of `@radix-ui/themes`.

<img width="641" alt="Screen Shot 2023-09-04 at 15 15 53" src="https://github.com/radix-ui/themes/assets/55989505/30c01da1-0be1-48bd-892f-eaa4f598b292">

**Comment by needim** [comment]
It looks like a documentation error. asChild shouldn't exist.

**Comment by kevinmitch14** [comment]
https://www.radix-ui.com/primitives/docs/guides/composition.
> All Radix primitive parts that render a DOM element accept an asChild prop.

 Although `<Table>` is not an official Radix primitive, some other components added in /themes do allow for the `asChild` prop such as `<Card>`,`<Button>`

**Comment by atodor84** [comment]
Select.Item from @radix-ui/themes does not work with asChild. React throw an error:
```
Uncaught Error: React.Children.only expected to receive a single React element child.
```

**Comment by vladmoroz** [comment]
> Select.Item from @radix-ui/themes does not work with asChild. React throw an error:
> 
> ```
> 
> Uncaught Error: React.Children.only expected to receive a single React element child.
> 
> ```

Sounds like you are trying to use `asChild` with multiple children. You can `asChild` into a single tag only.

**Comment by atodor84** [comment]
H2 @vladmoroz, you can try copying the example from https://www.radix-ui.com/themes/docs/components/select and change on the Select.Item and see the result. For example:
```
      <Select.Root defaultValue="apple">
        <Select.Trigger />
        <Select.Content>
          <Select.Label>Fruits</Select.Label>
          <Select.Item value="orange" asChild>
            <span>Orange</span>
          </Select.Item>
          <Select.Item value="apple">Apple</Select.Item>
          <Select.Item value="grape" disabled>
            Grape
          </Select.Item>

          <Select.Separator />
        </Select.Content>
      </Select.Root>
 ```
I am using "@radix-ui/themes": "^2.0.0"

**Comment by vladmoroz** [comment]
@kevinmitch14 could you give more detail on why you were trying to `asChild` table parts onto something?

**Comment by kevinmitch14** [comment]
I cant remember what I was trying to do tbh, and not sure if there is much of a use-case. However in the docs, `asChild` is mentioned as being available for `<Table />` parts.

**Comment by vladmoroz** [comment]
We'll update this in the docs for 3.0.0
