### ISSUE TITLE
Until a new `@radix-ui/themes` is released, dual-package hazard abounds

### ISSUE THREAD

**Issue by steveluscher** [radix-ui/themes#619]
* `@radix-ui/react-context` is up to `1.1.1`
* `@radix-ui/themes@3.1.4` specfies `1.1.0`
* When you have a project that uses both `@radix-ui/themes@3.1.4` _and_ `@radix-ui/react-context@1.1.1` **you will get both** `@radix-ui/react-context@1.1.1` _and_ `@radix-ui/react-context@1.1.0`.
* Context will be created with one version, and be looked up by `useContext` with a different version, resulting in the context not being found and errors like <code>`MenuSubTrigger` must be used within `Menu`</code> being thrown, spuriously.

Please release `@radix-ui/themes@3.1.5`.

**Comment by steveluscher** [comment]
You did this.

**Comment by arthur-fontaine** [comment]
I have this issue with 3.2.0 `"@radix-ui/themes": "^3.2.0",`. Do you have it too?
