### ISSUE TITLE
Strange Behavior on 3.1.5

### ISSUE THREAD

**Issue by joepetrillo** [radix-ui/themes#627]
Tried updating to 3.1.5 today in my next 15 project and noticed some strange behaviors.

Some things I noticed right away:

1. My tables were no longer taking up full width by default.
2. Dialogs were flashing while closing. (It would close and then you’d see a quick dark flash).
3. Site felt slower (maybe placebo?)

Reverting back to 3.1.4 fixed the issues.

Anyone else seeing this? Thanks!

**Comment by evanfrawley** [comment]
`<ScrollArea>`'s first child also now longer has the `min-width: 100%` value set, so it shrink's down the content's size and offsets all the content in the ScrollAreas. 

Reverting back to 3.1.4 now as well.

**Comment by daynewright** [comment]
Seeing the same issue. ^ the `<ScrollArea>` width needs to be reverted.  Moving to `3.1.4` is the answer for now.

**Comment by vasudev09** [comment]
I am facing the same issues in `3.1.6` .

For table full width you can try adding this in globals.css:
```
[data-radix-scroll-area-content] {
    min-width: 100% !important;
}
```

**Comment by chaance** [comment]
Dialog issue fixed in https://github.com/radix-ui/themes/pull/649. Feel free to open another more specific issue if there's anything else.
