### ISSUE TITLE
Changing breakpoint sizes

### ISSUE THREAD

**Issue by Sly777** [radix-ui/themes#63]
Hey Everyone, is there any way to change breakpoints on Radix/themes? I want to use different sizes on it. If there is no easy way, what if I use `custom-media` with PostCSS, will I have a chance to change the current ones and affect all theme structure?

https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/styles/breakpoints.css

**Comment by needim** [comment]
Right now I don't see any way to replace default breakpoints because they are using the postCSS plugin called custom-media. There are no generated CSS variables, and media queries are generated automatically.

Maybe in the next versions, breakpoints can be replaceable with the `<Theme />` component. or via CSS variables.

**Comment by vladmoroz** [comment]
We’d love to support this, but we need browsers to implement @custom-media first.
https://drafts.csswg.org/mediaqueries-5/#custom-mq

We don’t want to implement it by requiring a PostCSS setup on the consumer’s side.

> If there is no easy way, what if I use custom-media with PostCSS, will I have a chance to change the current ones and affect all theme structure?

Yeah, this would work if you fork Radix Themes into your project and compile the CSS from source.

**Comment by tunttunen** [comment]
What is the situation currently with this? Is there a way for you to e.g. even add more breakpoints or is this related to customized breakpoints? For example, can you add more breakpoints like 3xl, 4xl, 5xl?

**Comment by tunttunen** [comment]
> What is the situation currently with this? Is there a way for you to e.g. even add more breakpoints or is this related to customized breakpoints? For example, can you add more breakpoints like 3xl, 4xl, 5xl?

What is the situation currently with this? Is there a way for you to e.g. even add more breakpoints or is this related to customized breakpoints? For example, can you add more breakpoints like 3xl, 4xl, 5xl?

**Comment by tunttunen** [comment]
> We’d love to support this, but we need browsers to implement `@custom-media` first. https://drafts.csswg.org/mediaqueries-5/#custom-mq
> 
> We don’t want to implement it by requiring a PostCSS setup on the consumer’s side.
> 
> > If there is no easy way, what if I use custom-media with PostCSS, will I have a chance to change the current ones and affect all theme structure?
> 
> Yeah, this would work if you fork Radix Themes into your project and compile the CSS from source.

What is the situation currently with this? Is there a way for you to e.g. even add more breakpoints or is this related to customized breakpoints? For example, can you add more breakpoints like 3xl, 4xl, 5xl?

**Comment by seb-lean** [comment]
> but we need browsers to implement `@custom-media` first.

I think you will be waiting a long time! 😁
