### ISSUE TITLE
Theme works not good at safari

### ISSUE THREAD

**Issue by WaningJupiter** [radix-ui/themes#632]
Hello, 
I customized the theme colors and am using Radix Theme elements to build my site. In Safari, the theme doesn't render correctly compared to Firefox or Chrome. 

For example, all text should default to --gray-13, but in Safari, it defaults to --gray-1. This behavior is confusing. Here's a screenshot where none of the text is visible:
`safari` Version 14.1.1 (16611.2.7.1.4)
<img width="487" alt="Capture d’écran 2024-11-19 à 10 10 45" src="https://github.com/user-attachments/assets/643b13a7-40d5-402c-9bca-86337a2fdc57">
`safari` The text in the <input/> isn't visible either
<img width="487" alt="Capture d’écran 2024-11-19 à 10 13 18" src="https://github.com/user-attachments/assets/65d0d2f5-ff5f-4e70-b9b1-33d021288463">

`Firefox` Version 132.0.2 (64 bits)
<img width="487" alt="Capture d’écran 2024-11-19 à 10 10 26" src="https://github.com/user-attachments/assets/61beb3bc-c4db-4329-b430-8310d925f0dd">

**Comment by chaance** [comment]
Cannot reproduce with the info provided. If you can create a minimal reproduction I can investigate and reopen.
