### ISSUE TITLE
issue in yarn install and npm 404 package not found

### ISSUE THREAD

**Issue by Kadigh53** [radix-ui/themes#637]
Description
Encountering a 404 error when attempting to install specific Radix UI packages. These packages seem to be unavailable or not resolving correctly in the package registry.

Affected Packages
The following packages are affected:

@radix-ui/react-aspect-ratio - ^1.1.0
@radix-ui/react-avatar - ^1.1.1
@radix-ui/react-dialog - ^1.1.2
@radix-ui/react-slot - ^1.1.0
@radix-ui/react-toast - ^1.2.2
Steps to Reproduce
Run npm install or yarn add for any of the packages listed above.
Observe the 404 error in the terminal.
Expected Behavior
The packages should install successfully from the npm registry without any errors.

Actual Behavior
The following error message appears:

perl
Copy code
404 Not Found - GET https://registry.npmjs.org/@radix-ui/<package-name>
Environment
Node.js version: x.x.x
npm/Yarn version: x.x.x
Operating System: Your OS
Package Manager: npm or yarn
Additional Notes
I have confirmed that my internet connection is stable.
The issue persists across multiple systems and environments.
Could this be related to a recent update or registry configuration issue?
Please advise on how to resolve this issue or if the packages are temporarily unavailable.

**Comment by vAbdullh** [comment]
NPM is down for maintenance.
https://status.npmjs.org/

**Comment by chaance** [comment]
Not able to reproduce this unfortunately, but it sounds like it might be an issue with your local environment. If you can create an isolated repro, happy to re-open and look into it.
