### ISSUE TITLE
`TextField.Input` loses focus everytime `useState` refresh the state of the component

### ISSUE THREAD

**Issue by Miguelo981** [radix-ui/themes#64]
`TextField.Input` is losing focus everytime useState set is triggered `onChange`. This behavior doesn't happend in vanilla inputs using React. Is there any config I am missing or is this a bug?

```
const [projectBody, setProjectBody] = useState<ProjectForm>({
    name: "",
    description: "",
    category: "",
    budget: "",
  });

const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;

    setProjectBody({ ...projectBody, [name]: value });
 };

<form action="" method="POST" className="flex flex-col gap-4">
      <label htmlFor="name">Name *</label>
        <TextField.Input
          size="3"
          name="name"
          id="name"
          placeholder="Cool App..."
          onChange={handleInputChange}
        />
</form>
```
Project deps:

- Next: 13.4.19
- @radix-ui/themes: 1.1.2
- million: 2.6.0-beta.11

**Comment by needim** [comment]
created a sandbox to test this: https://codesandbox.io/s/radix-ui-themes-cra-issue-64-npkw42?file=/src/App.js

Input doesn't lose the focus in the react app maybe it is related to your next.js & million setup. Can you give more info so people repro?

**Comment by kevinmitch14** [comment]
Could be related to https://github.com/typehero/typehero/issues/612

**Comment by Miguelo981** [comment]
> created a sandbox to test this: https://codesandbox.io/s/radix-ui-themes-cra-issue-64-npkw42?file=/src/App.js
> 
> Input doesn't lose the focus in the react app maybe it is related to your next.js & million setup. Can you give more info so people repro?

I disabled million.js and now the form works fine =)
