### ISSUE TITLE
Screen flickering on Dialog closes | Radix Themes

### ISSUE THREAD

**Issue by mausam-giri** [radix-ui/themes#640]
### Current Behavior

Sample video, please notice the flickering I have provided the stackblitz project repo link please check.
https://github.com/user-attachments/assets/8aef7930-464f-470e-8ef7-16a7be11546d

### Expected behavior

I expected this to close smoothly without any flickering issue visible to the users.

### Reproducible example

[StackBlitz Project Link](https://stackblitz.com/edit/stackblitz-starters-fsfdnffv?file=app%2Fpage.tsx) https://stackblitz.com/edit/stackblitz-starters-fsfdnffv?file=app%2Fpage.tsx

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | themes  |  3.1.6  |
| React            | n/a     |  18.2.0 |
| Next             | n/a     |  13.5.1 |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     | v22.12.0|
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by chaance** [comment]
Fixed in #649, will ship in 1.2.0.
