### ISSUE TITLE
[Website] Android Firefox is Broken

### ISSUE THREAD

**Issue by qw-in** [radix-ui/themes#7]
On Android Firefox, I can't seem to scroll. Or whole sections of the homepage go black. Generally unusable - maybe the hug of death? 

Just the landing page 

I'll attach a video when I can (too large for Github)

**Comment by qw-in** [comment]
https://github.com/radix-ui/themes/assets/19194187/46653dac-25e8-4da9-9152-11d71e9f4c2e


Can confirm still happening today

**Comment by vladmoroz** [comment]
Hey, we just shipped a couple big performance improvements to the Radix homepage today. Could you check https://radix-ui.com and let me know if you still experience issues?

**Comment by qw-in** [comment]
@vladmoroz seems basically identical to chrome now, thanks!
