### ISSUE TITLE
next 13.4.2 - Hydration failure with Theme

### ISSUE THREAD

**Issue by archywillhe** [radix-ui/themes#71]
When I use `<Theme>` inside _app.tsx (from ` import { Theme } from '@radix-ui/themes'`)

I got this error:

> Hydration failed because the initial UI does not match what was rendered on the server.

Removing Theme gets rid of Hydration failure completely.

**Comment by archywillhe** [comment]
what could be the culprit here? (It was working fine earlier)

**Comment by vladmoroz** [comment]
https://www.radix-ui.com/themes/docs/theme/dark-mode#automatic-background-color
