### ISSUE TITLE
Decrease default css file size

### ISSUE THREAD

**Issue by tclain-pillar** [radix-ui/themes#74]
As far as I can tell, the recommended css file is 640kb+ unminified.

https://unpkg.com/browse/@radix-ui/themes@1.1.2/styles.css

Is there a way to build only the css we need for the component we import?

**Comment by emadabdulrahim** [comment]
Dunno if there's an easy tool to run to purge unused classes from the output bundle. If someone knows please post here :)

**Comment by iamkhan21** [comment]
> Dunno if there's an easy tool to run to purge unused classes from the output bundle. If someone knows please post here :)

Probably this one https://github.com/jowast/vite-plugin-purgecss

**Comment by vladmoroz** [comment]
Your best bet is [PurgeCSS](https://purgecss.com/), which analyzes your code and strips unused selectors.

gzipped + minified Radix Themes CSS is about 100kB. It's true that most apps won't use all of it, but it shouldn't be a tangible performance concern in most cases.

This is something we do want to improve, but it's not an immediate priority right now. I'll close the issue until we can prioritise it.

**Comment by grelas** [comment]
+1 to this. Would initially like to slowly introduce components like `Box` and `Flex` without having CSS included for other components. Definitely is the blocker for usage (can't use purgecss in our current ecosystem).
