### ISSUE TITLE
Support changing Grid columns with screen breakpoints 

### ISSUE THREAD

**Issue by ajdiyassin** [radix-ui/themes#86]
I did read the docs multiple times and I can't figure out how to do something like this.

For example:

````
<Grid columns={{ md: '12' }} gap={'5'}>

          <Flex direction={'column'} size={sm: 12, md: 8} >
          </Flex>

          <Flex direction={'column'}  size={sm: 12, md: 4} >
          </Flex>
 </Grid>

**Comment by kevinmitch14** [comment]
Not too easy to figure out, but follows same structure as [here](https://www.radix-ui.com/themes/docs/theme/breakpoints#usage).

> Most component size and layout props will accept an additional responsive object shape for modifying the given prop across breakpoints.

```js
<Grid
  columns={{
    sm: "1",
    md: "2",
    lg: "3",
    xl: "4",
  }}
>
```

```js
<Flex
  direction={{
    sm: "column",
    lg: "row",
  }}
  gap={{
  initial: "0",
  md: "4",
  }}
>
```

**Comment by ajdiyassin** [comment]
> Not too easy to figure out, but follows same structure as [here](https://www.radix-ui.com/themes/docs/theme/breakpoints#usage).
> 
> > Most component size and layout props will accept an additional responsive object shape for modifying the given prop across breakpoints.
> 
> ```js
> <Grid
>   columns={{
>     sm: "1",
>     md: "2",
>     lg: "3",
>     xl: "4",
>   }}
> >
> ```
> 
> ```js
> <Flex
>   direction={{
>     sm: "column",
>     lg: "row",
>   }}
>   gap={{
>   initial: "0",
>   md: "4",
>   }}
> >
> ```

But is it possible to change the grid children's span based on screen breakpoints?

**Comment by kevinmitch14** [comment]
Something like this? Keep in mind tailwind breakpoints are not the same as the Radix Themes breakpoints.

```js
<Grid columns={{initial: "1", sm: "3"}}>
  <div className="sm:col-span-2">1</div>
  <div>2</div>
  <div>3</div>
  <div className="sm:col-span-2">4</div>
</Grid>
```

**Comment by ajdiyassin** [comment]
Optimal solition something like what mantine v 7 is doing:
```
<Grid gutter={'xl'}>
      <Grid.Col span={{ base: 12, md: 9 }}></Grid.Col>
      <Grid.Col span={{ base: 12, md: 3 }}></Grid.Col>
</Grid>

**Comment by vladmoroz** [comment]
We plan to release this feature in a couple weeks

**Comment by vladmoroz** [comment]
Alright, this has been added in `2.1.0-rc.1`

See [changelog](https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/changelog.md) for the full list of updates.
