### ISSUE TITLE
Any changelog for the version 2.0.0-rc3?

### ISSUE THREAD

**Issue by Asuka109** [radix-ui/themes#88]
I found that the latest tag of @radix-ui/themes has been set to 2.0.0-rc3. Is this as expected? Where can I find the changelog for the 2.0?

![image](https://github.com/radix-ui/themes/assets/18379948/ee70ff6c-addf-4718-b854-92743357955a)

**Comment by vladmoroz** [comment]
That should have been published with "next" tag. I amended the tags and set latest to 1.1.2, but here's the changelog for 2.0.0-rc.3:
https://github.com/radix-ui/themes/blob/f293bf5de950a2206b1e46af579acb0ccc40c110/packages/radix-ui-themes/changelog.md

The changes will be documented more publicly when we release 2.0.0
