### ISSUE TITLE
[Remix] Named export 'Theme' not found

### ISSUE THREAD

**Issue by cleytoncarvalho** [radix-ui/themes#9]
Trying to use it with Remix but got the error:

import { Theme } from "@radix-ui/themes";

SyntaxError: Named export 'Theme' not found. The requested module '@radix-ui/themes' is a CommonJS module, which may not support all module.exports as named exports.

**Comment by NextThread** [comment]
can I work on this>??

**Comment by danestves** [comment]
Facing the same issue here

**Comment by lukemartin** [comment]
Strange, I'm using it fine in a small Remix app. Maybe you could create a reproducible repo example for others to test?

**Comment by danestves** [comment]
I'm using Remix with ESM, so I have to put `serverDependenciesToBundle: ['@radix-ui/themes'],` to be able to use it

**Comment by cleytoncarvalho** [comment]
> I'm using Remix with ESM, so I have to put `serverDependenciesToBundle: ['@radix-ui/themes'],` to be able to use it

I tried it but then got the error:

Error: Cannot find package 'classnames' imported from /apps/remix/build/index.js

**Comment by cleytoncarvalho** [comment]
I think this is a problem with Remix and ESM dependencies.

**Comment by fernandocanizo** [comment]
> > I'm using Remix with ESM, so I have to put `serverDependenciesToBundle: ['@radix-ui/themes'],` to be able to use it
> 
> I tried it but got the error:
> 
> Error: Cannot find package 'classnames' imported from /apps/remix/build/index.js

Same here on a Remix v2.3.1 project. Added it too, and then another one, but when I reach `@babel/runtime`, adding it to the bundle produces the same error:
```js
   serverDependenciesToBundle: [
     "@radix-ui/themes",
     "classnames",
     "@radix-ui/react-tooltip",
     "@babel/runtime",
   ],
```
Error before adding `@babel/runtime`:
```
Error: Cannot find package '@babel/runtime' imported from ./build/index.js
Did you mean to import @babel+runtime@7.23.4/node_modules/@babel/runtime/helpers/esm/extends.js?
```
Error after adding it:
```
Error: Cannot find package '@babel/runtime' imported from ./build/index.js
Did you mean to import @babel+runtime@7.23.4/node_modules/@babel/runtime/helpers/esm/extends.js?
```
So I reach an infinite loop there. :'(

Why did @cleytoncarvalho closed this? Did you found a solution?
